# MODEL: Evaluation and Baseline Performance

In [6]:
import subprocess
import sys
import os

def get_repo_root():
    return subprocess.check_output(['git', 'rev-parse', '--show-toplevel']).decode('utf-8').strip()
repo_root = get_repo_root()
print(repo_root)

src_path = os.path.join(repo_root, 'src')
# Add src_path to sys.path if not already present
if src_path not in sys.path:
    sys.path.insert(0, src_path)

/home/sagemaker-user/aai-540-su25-group4

In [16]:
# try importing src/utils
from utils.utils import parse_s3_uri
from utils.utils import generate_manifest_file

In [18]:
import boto3
import sagemaker
from sagemaker import get_execution_role
import pandas as pd
import json
from sagemaker.transformer import Transformer


role = get_execution_role()
print(role)

region = boto3.Session().region_name

s3_client = boto3.client("s3")
sm_client = boto3.client("sagemaker")

sess = sagemaker.Session()

# project bucket
bucket_name = "aai-540-data"

# sagemaker model name
sagemaker_model_name = "image-classification-2025-06-19-18-37-41-534"

# provide validation and test s3 folders,
s3_validation_path = f"s3://{bucket_name}/dev_split/validation"
val_key = "val-meta.csv"

s3_test_path = f"s3://{bucket_name}/dev_split/test"
test_key = "test-meta.csv"

# provide s3 full path to label_mapping.json use during training
s3_label_map_uri = f"s3://{bucket_name}/dev_split/label_mapping.json"

arn:aws:iam::324183265896:role/service-role/AmazonSageMaker-ExecutionRole-20250604T045982

In [19]:
# Generate Manifest File for Validation and Test Meta CSVs for Evaluation Via Batch Transform
generate_manifest_file(s3_input_csv = f"{s3_validation_path}/{val_key}", s3_images_loc = f"s3://{bucket_name}/cct_resized/")
generate_manifest_file(s3_input_csv = f"{s3_test_path}/{test_key}", s3_images_loc = f"s3://{bucket_name}/cct_resized/")

File uploaded to s3://aai-540-data/dev_split/validation/val-meta.manifest
File uploaded to s3://aai-540-data/dev_split/test/test-meta.manifest

In [21]:
# Transform the Validation Set First

s3_transform_manifest = f"{s3_validation_path}/val-meta.manifest"
s3_transform_out = f"{s3_validation_path}/batch_transform_out"

# initialize Tranformer
transformer = Transformer(
    model_name = sagemaker_model_name,
    instance_count=1,  # Number of instances
    instance_type="ml.g4dn.xlarge",  # Instance type
    output_path= s3_transform_out,  # Predictions output
    max_payload=10,  # Max payload size (MB)
    strategy="MultiRecord" , # for faster processing, but in real world, instance type can be ml.m5.xlarge and single record strategy is ok
    max_concurrent_transforms=10,
    sagemaker_session=sess,

    accept = 'txt/csv', # so output is generated in single file
    assemble_with='Line', # new line is generated for each prediction

)

In [23]:
# Transform the Validation Set

# batch transform images in manifest file
transformer.transform(
    data=s3_transform_manifest,
    data_type='ManifestFile', # provide list of s3uris of objects to be batch transformed
    content_type='application/x-image', 
    split_type='None', # because each object is an image file to be processed, no splitting needed
    logs=True,
    wait=True
)

INFO:sagemaker:Creating transform job with name: image-classification-2025-06-22-13-12-48-727

...................................Docker entrypoint called with argument(s): serve
Running default environment configuration script
Nvidia gpu devices, drivers and cuda toolkit versions (only available on hosts with GPU):
Sun Jun 22 13:18:32 2025
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.256.02   Driver Version: 470.256.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   26C    P8    11W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Checking for nvidia driver and cuda compatibility.
CUDA Compatibility driver provided.
Proceeding with compatibility check between driver, cuda-toolkit and cuda-compat.
Detected cuda-toolkit version: 11.1.
Detected cuda-compat version: 455.32.00.
Detected Nvidia driver version: 470.256.02.
Nvidia driver compatible with cuda-toolkit. Disabling cuda-compat.
/opt/amazon/lib/python3.8/site-packages/mxnet/model.py:97: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if num_device is 1 and 'dist' not in kvstore:
[06/22/2025 13:18:36 INFO 139884029794112] loaded entry point class algorithm.serve.server_config:config_api
[06/22/2025 13:18:36 INFO 139884029794112] loading entry points
[06/22/2025 13:18:36 INFO 139884029794112] loaded request iterator application/x-image
[06/22/2025 13:18:36 INFO 139884029794112] loaded request iterator image/jpeg
[06/22/2025 13:18:36 INFO 139884029794112] loaded request iterator image/png
[06/22/2025 13:18:36 INFO 139884029794112] loaded response encoder application/json
[06/22/2025 13:18:36 INFO 139884029794112] loaded response encoder application/jsonlines
[06/22/2025 13:18:36 INFO 139884029794112] loaded entry point class algorithm:model
[06/22/2025 13:18:36 INFO 139884029794112] Number of server workers: 3
[2025-06-22 13:18:36 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2025-06-22 13:18:36 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2025-06-22 13:18:36 +0000] [1] [INFO] Using worker: sync
[2025-06-22 13:18:36 +0000] [59] [INFO] Booting worker with pid: 59
[06/22/2025 13:18:36 INFO 139884029794112] loading model...
[06/22/2025 13:18:36 WARNING 139884029794112] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[06/22/2025 13:18:36 INFO 139884029794112] nvidia-smi: took 0.038 seconds to run.
[06/22/2025 13:18:36 INFO 139884029794112] nvidia-smi identified 1 GPUs.
[06/22/2025 13:18:36 INFO 139884029794112] Number of GPUs being used: 1
[06/22/2025 13:18:36 INFO 139884029794112] Using device: 0 for worker PID: 59
[06/22/2025 13:18:36 INFO 139884029794112] Looking for model file in /opt/ml/model
[06/22/2025 13:18:36 INFO 139884029794112] Loading /opt/ml/model/image-classification-0009.params
[2025-06-22 13:18:36 +0000] [80] [INFO] Booting worker with pid: 80
[06/22/2025 13:18:36 INFO 139884029794112] loading model...
[06/22/2025 13:18:36 WARNING 139884029794112] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[2025-06-22 13:18:36 +0000] [98] [INFO] Booting worker with pid: 98
[06/22/2025 13:18:36 INFO 139884029794112] loading model...
[06/22/2025 13:18:36 WARNING 139884029794112] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[06/22/2025 13:18:36 INFO 139884029794112] Using Context: gpu(0)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[06/22/2025 13:18:36 INFO 139884029794112] nvidia-smi: took 0.047 seconds to run.
[06/22/2025 13:18:36 INFO 139884029794112] nvidia-smi identified 1 GPUs.
[06/22/2025 13:18:36 INFO 139884029794112] Number of GPUs being used: 1
[06/22/2025 13:18:36 INFO 139884029794112] Using device: 0 for worker PID: 80
[06/22/2025 13:18:36 INFO 139884029794112] Looking for model file in /opt/ml/model
[06/22/2025 13:18:36 INFO 139884029794112] Loading /opt/ml/model/image-classification-0009.params
[06/22/2025 13:18:36 INFO 139884029794112] nvidia-smi: took 0.046 seconds to run.
[06/22/2025 13:18:36 INFO 139884029794112] nvidia-smi identified 1 GPUs.
[06/22/2025 13:18:36 INFO 139884029794112] Number of GPUs being used: 1
[06/22/2025 13:18:36 INFO 139884029794112] Using device: 0 for worker PID: 98
[06/22/2025 13:18:36 INFO 139884029794112] Looking for model file in /opt/ml/model
[06/22/2025 13:18:36 INFO 139884029794112] Loading /opt/ml/model/image-classification-0009.params
[06/22/2025 13:18:36 INFO 139884029794112] Using Context: gpu(0)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[06/22/2025 13:18:36 INFO 139884029794112] Using Context: gpu(0)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[06/22/2025 13:18:42 INFO 139884029794112] ...model loaded.
[06/22/2025 13:18:42 INFO 139884029794112] ...model loaded.
[06/22/2025 13:18:42 INFO 139884029794112] ...model loaded.
#metrics {"StartTime": 1750598322.4003093, "EndTime": 1750598322.424534, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"execution_parameters.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
[13:18:42] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[13:18:42] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[13:18:42] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
#metrics {"StartTime": 1750598322.4246728, "EndTime": 1750598323.215772, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.2158232, "EndTime": 1750598323.2276692, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598322.2756112, "EndTime": 1750598323.23053, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.2306292, "EndTime": 1750598323.2434244, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.2277398, "EndTime": 1750598323.2469306, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.243496, "EndTime": 1750598323.2575095, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.2470264, "EndTime": 1750598323.2575371, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.2577302, "EndTime": 1750598323.2682261, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.257588, "EndTime": 1750598323.2700343, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598322.3813934, "EndTime": 1750598323.2723532, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.2724292, "EndTime": 1750598323.4129064, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.270103, "EndTime": 1750598323.4994307, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.2682896, "EndTime": 1750598323.5466092, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.4129558, "EndTime": 1750598323.5483189, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.5466752, "EndTime": 1750598323.642665, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.499482, "EndTime": 1750598323.6571352, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.548369, "EndTime": 1750598323.662882, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.6572244, "EndTime": 1750598323.6841273, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.6842082, "EndTime": 1750598323.7095063, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.6629484, "EndTime": 1750598323.7111225, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.7095745, "EndTime": 1750598323.8302884, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.7111933, "EndTime": 1750598323.8319607, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.6428165, "EndTime": 1750598323.8401303, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.8303537, "EndTime": 1750598323.8454251, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.8321574, "EndTime": 1750598323.8579497, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.8457184, "EndTime": 1750598323.861398, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.8402872, "EndTime": 1750598323.8734195, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.8614588, "EndTime": 1750598323.877495, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.858019, "EndTime": 1750598323.8825984, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.8737643, "EndTime": 1750598323.8835604, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.8826709, "EndTime": 1750598323.8975914, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.8976622, "EndTime": 1750598323.9144647, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.8775394, "EndTime": 1750598323.92008, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.9145617, "EndTime": 1750598323.9614859, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.9201508, "EndTime": 1750598323.9647808, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.8836155, "EndTime": 1750598323.967016, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.9615474, "EndTime": 1750598323.9739215, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.9653842, "EndTime": 1750598323.9777598, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.9671667, "EndTime": 1750598323.9782743, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.9739985, "EndTime": 1750598323.9945638, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.97783, "EndTime": 1750598324.0086277, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.9946325, "EndTime": 1750598324.0110366, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598323.9783351, "EndTime": 1750598324.012115, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598324.0123768, "EndTime": 1750598324.0361528, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598324.0111892, "EndTime": 1750598324.0705004, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598324.0362318, "EndTime": 1750598324.0772648, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598324.0089362, "EndTime": 1750598324.1024952, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598324.0708492, "EndTime": 1750598324.1140816, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750598324.1141868, "EndTime": 1750598324.1272829, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}

In [31]:
# Evaluate the Prediction Results via ScriptProcessing
from sagemaker.processing import ScriptProcessor, ProcessingInput, ProcessingOutput

image_uri = sagemaker.image_uris.retrieve(
    framework='sklearn',        # or 'xgboost', 'pytorch', etc.
    region=region,
    version='1.2-1',            # Specify the version you need
    py_version='py3',           # Specify Python version if required
       # Use 'processing' for processing jobs
)

print(image_uri)

# Define your processing container (can use a built-in or custom image)
script_processor = ScriptProcessor(
    command=['python3'],
    image_uri=image_uri,  # e.g., a scikit-learn or custom image
    role=role,
    instance_count=1,
    instance_type='ml.m5.xlarge',
    
)

INFO:sagemaker.image_uris:Defaulting to only supported image scope: cpu.

683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-scikit-learn:1.2-1-cpu-py3

In [32]:

# Run evaluation script
s3_evaluation_out = f"{s3_validation_path}/evaluation"
s3_true_meta_uri = f"{s3_validation_path}/{val_key}"

script_processor.run(
    code='../../src/evaluation/evaluate.py',  # Your processing script
    inputs=[
        # S3 location of batch transform predictions files
        ProcessingInput(
            source=s3_transform_out,       # S3 bucket with predictions
            destination='/opt/ml/processing/input_predictions'        # Where the script will read input
        ),
        
        # S3 location of the ground truth labels for the images in this set
        ProcessingInput(
            source=s3_true_meta_uri,
            destination='/opt/ml/processing/true_labels'
        ),

        # Label Mapping
        ProcessingInput(
            source=s3_label_map_uri,
            destination='/opt/ml/processing/label_mapping'
        )
    ],
    outputs=[
        ProcessingOutput(
            source='/opt/ml/processing/output',           # Where the script will write output
            destination=s3_evaluation_out    # S3 bucket to store results
        )
    ]
)

INFO:sagemaker:Creating processing-job with name sagemaker-scikit-learn-2025-06-22-14-11-22-529

...........[2025-06-22 14:13:14.822629] Script has started.
INFO:root:Script has started at 2025-06-22 14:13:14.822659.
Number of files in /opt/ml/processing/input_predictions: 6048
Processed 3 prediction files so far, here is the dataframe
                                     filename                                         prediction
0  5971fad6-23d2-11e8-a6a3-ec086b02610b_0.jpg  [1.4443931206642438e-07, 7.355709097378593e-11...
1  59dc24e9-23d2-11e8-a6a3-ec086b02610b_0.jpg  [9.587807170419183e-08, 6.917158401620328e-09,...
2  5968c1b0-23d2-11e8-a6a3-ec086b02610b_0.jpg  [0.00269423238933, 3.909136648871936e-05, 2.80...
                                     filename                                         prediction
0  5971fad6-23d2-11e8-a6a3-ec086b02610b_0.jpg  [1.4443931206642438e-07, 7.355709097378593e-11...
1  59dc24e9-23d2-11e8-a6a3-ec086b02610b_0.jpg  [9.587807170419183e-08, 6.917158401620328e-09,...
2  5968c1b0-23d2-11e8-a6a3-ec086b02610b_0.jpg  [0.00269423238933, 3.909136648871936e-05, 2.80...
3  58ac0c00-23d2-11e8-a6a3-ec086b02610b_0.jpg  [2.728685604292541e-13, 4.5417524450509783e-13...
4  59104aee-23d2-11e8-a6a3-ec086b02610b_0.jpg  [4.888672474646917e-13, 2.400434295779519e-09,...
pred probs df shape:(6048, 2)
 (step 1) pred probs df shape: (6048, 2)
 (step 2) True Labels data shape: (6048, 8)
 (step3) Merged data shape : (6048, 9)
 (step4) Merged data shape with preds: (6048, 11)
 (step5) METRICS CALCULATION
 (step5.1) Class-Restricted metrics - Evaluate only on labels available during training
 (step5.1) class_restriced df shape : (6048, 11)
              precision    recall  f1-score   support
        bird       0.32      0.73      0.45        26
      bobcat       0.81      0.87      0.84       454
         car       1.00      1.00      1.00       424
         cat       0.75      0.82      0.79       511
      coyote       0.88      0.84      0.86       668
        deer       1.00      0.80      0.89         5
         dog       0.86      0.75      0.80       380
       empty       0.00      0.00      0.00        13
     opossum       0.99      0.92      0.95      1822
      rabbit       0.82      0.95      0.88       271
     raccoon       0.90      0.92      0.91      1052
      rodent       0.77      0.88      0.82        58
       skunk       0.97      0.88      0.92       195
    squirrel       0.72      0.94      0.82       169
    accuracy                           0.89      6048
   macro avg       0.77      0.81      0.78      6048
weighted avg       0.90      0.89      0.89      6048
 (step5.2) Novelty Ratio Metric: portion of the new dataset that is unfamiliar to the model given a confidence threshold=0.7
 (step5.2) novelty ratio : 0.07407407407407407
Done executing script

----
### Model Comparison (on Validation Set) & Selection

-----
### Check Performance on Test Set of the selected Model

In [33]:
# Transform the Test Set
s3_transform_manifest = f"{s3_test_path}/test-meta.manifest"
s3_transform_out = f"{s3_test_path}/batch_transform_out"

# initialize Tranformer
transformer1 = Transformer(
    model_name = sagemaker_model_name,
    instance_count=1,  # Number of instances
    instance_type="ml.g4dn.xlarge",  # Instance type
    output_path= s3_transform_out,  # Predictions output
    max_payload=10,  # Max payload size (MB)
    strategy="MultiRecord" , # for faster processing, but in real world, instance type can be ml.m5.xlarge and single record strategy is ok
    max_concurrent_transforms=10,
    sagemaker_session=sess,

    accept = 'txt/csv', # so output is generated in single file
    assemble_with='Line', # new line is generated for each prediction

)

# batch transform images in manifest file
transformer1.transform(
    data=s3_transform_manifest,
    data_type='ManifestFile', # provide list of s3uris of objects to be batch transformed
    content_type='application/x-image', 
    split_type='None', # because each object is an image file to be processed, no splitting needed
    logs=True,
    wait=True
)

INFO:sagemaker:Creating transform job with name: image-classification-2025-06-22-14-19-58-779

....................................Docker entrypoint called with argument(s): serve
Running default environment configuration script
Nvidia gpu devices, drivers and cuda toolkit versions (only available on hosts with GPU):
Sun Jun 22 14:25:56 2025
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.256.02   Driver Version: 470.256.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   34C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Checking for nvidia driver and cuda compatibility.
CUDA Compatibility driver provided.
Proceeding with compatibility check between driver, cuda-toolkit and cuda-compat.
Detected cuda-toolkit version: 11.1.
Detected cuda-compat version: 455.32.00.
Detected Nvidia driver version: 470.256.02.
Nvidia driver compatible with cuda-toolkit. Disabling cuda-compat.
/opt/amazon/lib/python3.8/site-packages/mxnet/model.py:97: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if num_device is 1 and 'dist' not in kvstore:
[06/22/2025 14:26:00 INFO 140302074255168] loaded entry point class algorithm.serve.server_config:config_api
[06/22/2025 14:26:00 INFO 140302074255168] loading entry points
[06/22/2025 14:26:00 INFO 140302074255168] loaded request iterator application/x-image
[06/22/2025 14:26:00 INFO 140302074255168] loaded request iterator image/jpeg
[06/22/2025 14:26:00 INFO 140302074255168] loaded request iterator image/png
[06/22/2025 14:26:00 INFO 140302074255168] loaded response encoder application/json
[06/22/2025 14:26:00 INFO 140302074255168] loaded response encoder application/jsonlines
[06/22/2025 14:26:00 INFO 140302074255168] loaded entry point class algorithm:model
[06/22/2025 14:26:00 INFO 140302074255168] Number of server workers: 3
[2025-06-22 14:26:00 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2025-06-22 14:26:00 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2025-06-22 14:26:00 +0000] [1] [INFO] Using worker: sync
[2025-06-22 14:26:00 +0000] [60] [INFO] Booting worker with pid: 60
[06/22/2025 14:26:00 INFO 140302074255168] loading model...
[06/22/2025 14:26:00 WARNING 140302074255168] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[06/22/2025 14:26:00 INFO 140302074255168] nvidia-smi: took 0.031 seconds to run.
[06/22/2025 14:26:00 INFO 140302074255168] nvidia-smi identified 1 GPUs.
[06/22/2025 14:26:00 INFO 140302074255168] Number of GPUs being used: 1
[06/22/2025 14:26:00 INFO 140302074255168] Using device: 0 for worker PID: 60
[06/22/2025 14:26:00 INFO 140302074255168] Looking for model file in /opt/ml/model
[06/22/2025 14:26:00 INFO 140302074255168] Loading /opt/ml/model/image-classification-0009.params
[2025-06-22 14:26:00 +0000] [81] [INFO] Booting worker with pid: 81
[06/22/2025 14:26:00 INFO 140302074255168] loading model...
[06/22/2025 14:26:00 WARNING 140302074255168] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[06/22/2025 14:26:00 INFO 140302074255168] nvidia-smi: took 0.037 seconds to run.
[06/22/2025 14:26:00 INFO 140302074255168] nvidia-smi identified 1 GPUs.
[2025-06-22 14:26:00 +0000] [102] [INFO] Booting worker with pid: 102
[06/22/2025 14:26:00 INFO 140302074255168] Number of GPUs being used: 1
[06/22/2025 14:26:00 INFO 140302074255168] Using device: 0 for worker PID: 81
[06/22/2025 14:26:00 INFO 140302074255168] Looking for model file in /opt/ml/model
[06/22/2025 14:26:00 INFO 140302074255168] loading model...
[06/22/2025 14:26:00 WARNING 140302074255168] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[06/22/2025 14:26:00 INFO 140302074255168] Loading /opt/ml/model/image-classification-0009.params
[06/22/2025 14:26:00 INFO 140302074255168] Using Context: gpu(0)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[06/22/2025 14:26:00 INFO 140302074255168] nvidia-smi: took 0.036 seconds to run.
[06/22/2025 14:26:00 INFO 140302074255168] nvidia-smi identified 1 GPUs.
[06/22/2025 14:26:00 INFO 140302074255168] Number of GPUs being used: 1
[06/22/2025 14:26:00 INFO 140302074255168] Using device: 0 for worker PID: 102
[06/22/2025 14:26:00 INFO 140302074255168] Looking for model file in /opt/ml/model
[06/22/2025 14:26:00 INFO 140302074255168] Loading /opt/ml/model/image-classification-0009.params
[06/22/2025 14:26:00 INFO 140302074255168] Using Context: gpu(0)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[06/22/2025 14:26:00 INFO 140302074255168] Using Context: gpu(0)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[06/22/2025 14:26:06 INFO 140302074255168] ...model loaded.
[06/22/2025 14:26:06 INFO 140302074255168] ...model loaded.
[06/22/2025 14:26:06 INFO 140302074255168] ...model loaded.
#metrics {"StartTime": 1750602366.0833123, "EndTime": 1750602366.1528313, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"execution_parameters.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
[14:26:06] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[14:26:06] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[14:26:06] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
#metrics {"StartTime": 1750602366.1166484, "EndTime": 1750602366.9263535, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.9268663, "EndTime": 1750602366.9375975, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.1039135, "EndTime": 1750602366.942993, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.9379668, "EndTime": 1750602366.9473445, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.1531615, "EndTime": 1750602366.954085, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.9474034, "EndTime": 1750602366.9567416, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.9430952, "EndTime": 1750602366.9598522, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
[06/22/2025 14:26:06 INFO 140302074255168] ...model loaded.
[06/22/2025 14:26:06 INFO 140302074255168] ...model loaded.
[06/22/2025 14:26:06 INFO 140302074255168] ...model loaded.
#metrics {"StartTime": 1750602366.0833123, "EndTime": 1750602366.1528313, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"execution_parameters.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
[14:26:06] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[14:26:06] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[14:26:06] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
#metrics {"StartTime": 1750602366.1166484, "EndTime": 1750602366.9263535, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.9268663, "EndTime": 1750602366.9375975, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.1039135, "EndTime": 1750602366.942993, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.9379668, "EndTime": 1750602366.9473445, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.1531615, "EndTime": 1750602366.954085, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.9474034, "EndTime": 1750602366.9567416, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.9430952, "EndTime": 1750602366.9598522, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.9541512, "EndTime": 1750602366.9644556, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.9567823, "EndTime": 1750602366.966723, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.96014, "EndTime": 1750602366.9697793, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.9541512, "EndTime": 1750602366.9644556, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.9567823, "EndTime": 1750602366.966723, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.96014, "EndTime": 1750602366.9697793, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.9645178, "EndTime": 1750602367.252042, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.9698427, "EndTime": 1750602367.2526526, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602366.9667907, "EndTime": 1750602367.2539444, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602367.2527006, "EndTime": 1750602367.266201, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602367.2662592, "EndTime": 1750602367.3580801, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602367.253005, "EndTime": 1750602367.360597, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602367.2540054, "EndTime": 1750602367.371451, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602367.3719027, "EndTime": 1750602367.4395976, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602367.3610854, "EndTime": 1750602367.4647255, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602367.464774, "EndTime": 1750602367.4806216, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602367.3584716, "EndTime": 1750602367.5556917, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602367.4397185, "EndTime": 1750602367.5846722, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602367.5557427, "EndTime": 1750602367.5857553, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602367.4807467, "EndTime": 1750602367.5863376, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602367.5858226, "EndTime": 1750602367.5956957, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602367.584971, "EndTime": 1750602367.599496, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602367.586395, "EndTime": 1750602367.6066163, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602367.5997305, "EndTime": 1750602367.6145525, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602367.595758, "EndTime": 1750602367.6154745, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602367.6066878, "EndTime": 1750602367.6170058, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602367.6146145, "EndTime": 1750602367.6258404, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602367.6259012, "EndTime": 1750602367.6395092, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750602367.6171494, "EndTime": 1750602367.658384, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}

In [34]:
# Run Evaluation Script to evaluate all metrics

image_uri = sagemaker.image_uris.retrieve(
    framework='sklearn',        # or 'xgboost', 'pytorch', etc.
    region=region,
    version='1.2-1',            # Specify the version you need
    py_version='py3',           # Specify Python version if required
       # Use 'processing' for processing jobs
)
print(image_uri)
# Define your processing container (can use a built-in or custom image)
script_processor1 = ScriptProcessor(
    command=['python3'],
    image_uri=image_uri,  # e.g., a scikit-learn or custom image
    role=role,
    instance_count=1,
    instance_type='ml.m5.xlarge',
    
)

# Run the processing job on the validation prediction set
s3_evaluation_out = f"{s3_test_path}/evaluation"
s3_true_meta_uri = f"{s3_test_path}/{test_key}"

script_processor1.run(
    code='../../src/evaluation/evaluate.py',  # Your processing script
    inputs=[
        # S3 location of batch transform predictions files
        ProcessingInput(
            source=s3_transform_out,       # S3 bucket with predictions
            destination='/opt/ml/processing/input_predictions'        # Where the script will read input in local container
        ),
        
        # S3 location of the ground truth labels for the images in this set
        ProcessingInput(
            source=s3_true_meta_uri,
            destination='/opt/ml/processing/true_labels'
        ),

        # Label Mapping
        ProcessingInput(
            source=s3_label_map_uri,
            destination='/opt/ml/processing/label_mapping'
        )
    ],
    outputs=[
        ProcessingOutput(
            source='/opt/ml/processing/output',           # Where the script will write output files in local container
            destination=s3_evaluation_out    # S3 bucket to store results
        )
    ]
)

INFO:sagemaker.image_uris:Defaulting to only supported image scope: cpu.

683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-scikit-learn:1.2-1-cpu-py3

INFO:sagemaker:Creating processing-job with name sagemaker-scikit-learn-2025-06-22-14-30-07-960

.............[2025-06-22 14:32:13.275552] Script has started.
INFO:root:Script has started at 2025-06-22 14:32:13.275586.
Number of files in /opt/ml/processing/input_predictions: 7932
pred probs df shape:(7932, 2)
 (step 1) pred probs df shape: (7932, 2)
 (step 2) True Labels data shape: (7932, 8)
 (step3) Merged data shape : (7932, 9)
 (step4) Merged data shape with preds: (7932, 11)
 (step5) METRICS CALCULATION
 (step5.1) Class-Restricted metrics - Evaluate only on labels available during training
 (step5.1) class_restriced df shape : (7804, 11)
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
              precision    recall  f1-score   support
      badger       0.00      0.00      0.00         4
        bird       0.29      0.50      0.37        54
      bobcat       0.75      0.83      0.79       569
         car       1.00      0.99      0.99        85
         cat       0.68      0.72      0.70       828
      coyote       0.85      0.84      0.85      1199
        deer       1.00      0.47      0.64        17
         dog       0.62      0.58      0.60       395
       empty       0.00      0.00      0.00         8
     opossum       0.99      0.90      0.95      3092
      rabbit       0.77      0.90      0.83       298
     raccoon       0.83      0.91      0.87       737
      rodent       0.68      0.78      0.72        81
       skunk       0.86      0.82      0.84        51
    squirrel       0.73      0.86      0.79       386
    accuracy                           0.85      7804
   macro avg       0.67      0.67      0.66      7804
weighted avg       0.86      0.85      0.85      7804
 (step5.2) Novelty Ratio Metric: portion of the new dataset that is unfamiliar to the model given a confidence threshold=0.7
 (step5.2) novelty ratio : 0.09934442763489662
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
Done executing script

------

### Performance Summary on Validation and Test Sets

In [40]:
# validation set
s3_metrics_uri = f"{s3_validation_path}/evaluation/multiclass_metrics.json"
s3_class_report_uri = f"{s3_validation_path}/evaluation/restricted_class_report.csv"
val_metrics = pd.read_json(s3_metrics_uri)
val_class_report = pd.read_csv(s3_class_report_uri)
display(val_metrics)
display(val_class_report)

                               multiclass_classification_metrics
accuracy       {'value': 0.8903769841269841, 'standard_deviat...
f1-weighted    {'value': 0.892783336735068, 'standard_deviati...
novelty_ratio  {'value': 0.074074074074074, 'standard_deviati...

      Unnamed: 0  precision    recall  f1-score      support
0           bird   0.322034  0.730769  0.447059    26.000000
1         bobcat   0.813525  0.874449  0.842887   454.000000
2            car   1.000000  1.000000  1.000000   424.000000
3            cat   0.754955  0.819961  0.786116   511.000000
4         coyote   0.877934  0.839820  0.858454   668.000000
5           deer   1.000000  0.800000  0.888889     5.000000
6            dog   0.861446  0.752632  0.803371   380.000000
7          empty   0.000000  0.000000  0.000000    13.000000
8        opossum   0.990533  0.918771  0.953303  1822.000000
9         rabbit   0.818471  0.948339  0.878632   271.000000
10       raccoon   0.901685  0.915399  0.908491  1052.000000
11        rodent   0.772727  0.879310  0.822581    58.000000
12         skunk   0.971591  0.876923  0.921833   195.000000
13      squirrel   0.722727  0.940828  0.817481   169.000000
14      accuracy   0.890377  0.890377  0.890377     0.890377
15     macro avg   0.771973  0.806943  0.780650  6048.000000
16  weighted avg   0.899116  0.890377  0.892783  6048.000000

In [39]:
# test
s3_metrics_uri = f"{s3_test_path}/evaluation/multiclass_metrics.json"
s3_class_report_uri = f"{s3_test_path}/evaluation/restricted_class_report.csv"
test_metrics = pd.read_json(s3_metrics_uri)
test_class_report = pd.read_csv(s3_class_report_uri)
display(test_metrics)
display(test_class_report)

                               multiclass_classification_metrics
accuracy       {'value': 0.845079446437724, 'standard_deviati...
f1-weighted    {'value': 0.8479535389038411, 'standard_deviat...
novelty_ratio  {'value': 0.09934442763489601, 'standard_devia...

      Unnamed: 0  precision    recall  f1-score      support
0         badger   0.000000  0.000000  0.000000     4.000000
1           bird   0.293478  0.500000  0.369863    54.000000
2         bobcat   0.751189  0.833040  0.790000   569.000000
3            car   1.000000  0.988235  0.994083    85.000000
4            cat   0.683429  0.722222  0.702290   828.000000
5         coyote   0.853866  0.838198  0.845960  1199.000000
6           deer   1.000000  0.470588  0.640000    17.000000
7            dog   0.624658  0.577215  0.600000   395.000000
8          empty   0.000000  0.000000  0.000000     8.000000
9        opossum   0.991835  0.903622  0.945676  3092.000000
10        rabbit   0.767908  0.899329  0.828439   298.000000
11       raccoon   0.832921  0.913161  0.871197   737.000000
12        rodent   0.677419  0.777778  0.724138    81.000000
13         skunk   0.857143  0.823529  0.840000    51.000000
14      squirrel   0.733925  0.857513  0.790920   386.000000
15      accuracy   0.845079  0.845079  0.845079     0.845079
16     macro avg   0.671185  0.673629  0.662838  7804.000000
17  weighted avg   0.855076  0.845079  0.847954  7804.000000

In [41]:
!pwd

/home/sagemaker-user/aai-540-su25-group4/experiments/geoffrey