# MODEL Evaluation

In [1]:
import boto3
import sagemaker
from sagemaker import get_execution_role
import pandas as pd
import json
from sagemaker.transformer import Transformer


role = get_execution_role()
print(role)

region = boto3.Session().region_name

s3_client = boto3.client("s3")
sm_client = boto3.client("sagemaker")

sess = sagemaker.Session()

# project bucket
bucket_name = "aai-540-data"

# specify validation images via manifest file
# image source and lst files
#images_prefix = "cct_resized"
#s3_images_location = f"s3://{bucket_name}/{images_prefix}/"
#s3_validation_manifest = f"s3://{bucket_name}/dev_split/validation_manifest.json"
#s3_validation_manifest = f"s3://{bucket_name}/dev_split/validation.manifest"

# input images to for batch transform job via manifest file
# s3_transform_manifest = f"s3://{bucket_name}/tmp/val_manifest.json"
s3_transform_manifest = f"s3://{bucket_name}/tmp/manifest.json"

# location of predictions
s3_transform_out = f"s3://{bucket_name}/tmp/transform_output/"

sagemaker.config INFO - Not applying SDK defaults from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/sagemaker-user/.config/sagemaker/config.yaml
arn:aws:iam::324183265896:role/service-role/AmazonSageMaker-ExecutionRole-20250604T045982

In [2]:
# load the model name to be used, must be in sagemaker
sagemaker_model_name = "image-classification-2025-06-19-16-11-57-811"

# initialize Tranformer
transformer = Transformer(
    model_name = sagemaker_model_name,
    instance_count=1,  # Number of instances
    instance_type="ml.g4dn.xlarge",  # Instance type
    output_path=s3_transform_out,  # Predictions output
    #assemble_with='Line',
    #accept='application/json',
    max_payload=10,  # Max payload size (MB)
    strategy="MultiRecord" ,
    max_concurrent_transforms=10,
    sagemaker_session=sess
)

In [3]:
%%time

# batch transform images in manifest file
transformer.transform(
    data=s3_transform_manifest,
    data_type='ManifestFile', # provide list of s3uris of objects to be batch transformed
    content_type='application/x-image', 
    split_type='None', # because each object is an image file to be processed, no splitting needed
    accept = 'text/csv', # output file format
    logs=True,
    wait=True
)

INFO:sagemaker:Creating transform job with name: image-classification-2025-06-21-08-04-58-044

...................................Docker entrypoint called with argument(s): serve
Running default environment configuration script
Nvidia gpu devices, drivers and cuda toolkit versions (only available on hosts with GPU):
Sat Jun 21 08:10:49 2025
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.256.02   Driver Version: 470.256.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   31C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Checking for nvidia driver and cuda compatibility.
CUDA Compatibility driver provided.
Proceeding with compatibility check between driver, cuda-toolkit and cuda-compat.
Detected cuda-toolkit version: 11.1.
Detected cuda-compat version: 455.32.00.
Detected Nvidia driver version: 470.256.02.
Nvidia driver compatible with cuda-toolkit. Disabling cuda-compat.
/opt/amazon/lib/python3.8/site-packages/mxnet/model.py:97: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if num_device is 1 and 'dist' not in kvstore:
[06/21/2025 08:10:52 INFO 140062819366720] loaded entry point class algorithm.serve.server_config:config_api
[06/21/2025 08:10:52 INFO 140062819366720] loading entry points
[06/21/2025 08:10:52 INFO 140062819366720] loaded request iterator application/x-image
[06/21/2025 08:10:52 INFO 140062819366720] loaded request iterator image/jpeg
[06/21/2025 08:10:52 INFO 140062819366720] loaded request iterator image/png
[06/21/2025 08:10:52 INFO 140062819366720] loaded response encoder application/json
[06/21/2025 08:10:52 INFO 140062819366720] loaded response encoder application/jsonlines
[06/21/2025 08:10:52 INFO 140062819366720] loaded entry point class algorithm:model
[06/21/2025 08:10:52 INFO 140062819366720] Number of server workers: 3
[2025-06-21 08:10:52 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2025-06-21 08:10:52 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2025-06-21 08:10:52 +0000] [1] [INFO] Using worker: sync
[2025-06-21 08:10:52 +0000] [60] [INFO] Booting worker with pid: 60
[06/21/2025 08:10:52 INFO 140062819366720] loading model...
[06/21/2025 08:10:52 WARNING 140062819366720] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[06/21/2025 08:10:53 INFO 140062819366720] nvidia-smi: took 0.031 seconds to run.
[06/21/2025 08:10:53 INFO 140062819366720] nvidia-smi identified 1 GPUs.
[06/21/2025 08:10:53 INFO 140062819366720] Number of GPUs being used: 1
[06/21/2025 08:10:53 INFO 140062819366720] Using device: 0 for worker PID: 60
[06/21/2025 08:10:53 INFO 140062819366720] Looking for model file in /opt/ml/model
[06/21/2025 08:10:53 INFO 140062819366720] Loading /opt/ml/model/image-classification-0009.params
[2025-06-21 08:10:53 +0000] [81] [INFO] Booting worker with pid: 81
[06/21/2025 08:10:53 INFO 140062819366720] loading model...
[06/21/2025 08:10:53 WARNING 140062819366720] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[06/21/2025 08:10:53 INFO 140062819366720] nvidia-smi: took 0.034 seconds to run.
[06/21/2025 08:10:53 INFO 140062819366720] nvidia-smi identified 1 GPUs.
[06/21/2025 08:10:53 INFO 140062819366720] Number of GPUs being used: 1
[06/21/2025 08:10:53 INFO 140062819366720] Using device: 0 for worker PID: 81
[06/21/2025 08:10:53 INFO 140062819366720] Looking for model file in /opt/ml/model
[06/21/2025 08:10:53 INFO 140062819366720] Loading /opt/ml/model/image-classification-0009.params
[2025-06-21 08:10:53 +0000] [102] [INFO] Booting worker with pid: 102
[06/21/2025 08:10:53 INFO 140062819366720] loading model...
[06/21/2025 08:10:53 WARNING 140062819366720] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[06/21/2025 08:10:53 INFO 140062819366720] nvidia-smi: took 0.038 seconds to run.
[06/21/2025 08:10:53 INFO 140062819366720] nvidia-smi identified 1 GPUs.
[06/21/2025 08:10:53 INFO 140062819366720] Number of GPUs being used: 1
[06/21/2025 08:10:53 INFO 140062819366720] Using device: 0 for worker PID: 102
[06/21/2025 08:10:53 INFO 140062819366720] Looking for model file in /opt/ml/model
[06/21/2025 08:10:53 INFO 140062819366720] Loading /opt/ml/model/image-classification-0009.params
[06/21/2025 08:10:53 INFO 140062819366720] Using Context: gpu(0)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[06/21/2025 08:10:53 INFO 140062819366720] Using Context: gpu(0)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[06/21/2025 08:10:53 INFO 140062819366720] Using Context: gpu(0)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[06/21/2025 08:10:59 INFO 140062819366720] ...model loaded.
[06/21/2025 08:10:59 INFO 140062819366720] ...model loaded.
#metrics {"StartTime": 1750493459.0176322, "EndTime": 1750493459.0391445, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"execution_parameters.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
[06/21/2025 08:10:59 INFO 140062819366720] ...model loaded.
[06/21/2025 08:10:59 INFO 140062819366720] ...model loaded.
[08:10:59] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[08:10:59] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[08:10:59] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
#metrics {"StartTime": 1750493459.063425, "EndTime": 1750493459.84202, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.0392437, "EndTime": 1750493459.850921, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.0176322, "EndTime": 1750493459.0391445, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"execution_parameters.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
[06/21/2025 08:10:59 INFO 140062819366720] ...model loaded.
[06/21/2025 08:10:59 INFO 140062819366720] ...model loaded.
[08:10:59] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[08:10:59] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[08:10:59] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
#metrics {"StartTime": 1750493459.063425, "EndTime": 1750493459.84202, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.0392437, "EndTime": 1750493459.850921, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.8421025, "EndTime": 1750493459.8536313, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.850985, "EndTime": 1750493459.8616295, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.8536935, "EndTime": 1750493459.8681986, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.8617544, "EndTime": 1750493459.8728635, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.8682513, "EndTime": 1750493459.8780782, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.8729348, "EndTime": 1750493459.8839245, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.8781328, "EndTime": 1750493459.8876731, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.0680594, "EndTime": 1750493459.8916523, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.8421025, "EndTime": 1750493459.8536313, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.850985, "EndTime": 1750493459.8616295, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.8536935, "EndTime": 1750493459.8681986, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.8617544, "EndTime": 1750493459.8728635, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.8682513, "EndTime": 1750493459.8780782, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.8729348, "EndTime": 1750493459.8839245, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.8781328, "EndTime": 1750493459.8876731, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.0680594, "EndTime": 1750493459.8916523, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
2025-06-21T08:10:59.058:[sagemaker logs]: MaxConcurrentTransforms=10, MaxPayloadInMB=10, BatchStrategy=MULTI_RECORD
#metrics {"StartTime": 1750493459.8917258, "EndTime": 1750493460.0344143, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.883985, "EndTime": 1750493460.035326, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493460.0353684, "EndTime": 1750493460.1217542, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.8877323, "EndTime": 1750493460.126577, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493460.0344613, "EndTime": 1750493460.127323, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493460.121809, "EndTime": 1750493460.2094488, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493460.2095075, "EndTime": 1750493460.2916806, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493460.1273942, "EndTime": 1750493460.2941673, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493460.2945306, "EndTime": 1750493460.3295712, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493460.3297117, "EndTime": 1750493460.3554747, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493460.2918, "EndTime": 1750493460.484852, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.8917258, "EndTime": 1750493460.0344143, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.883985, "EndTime": 1750493460.035326, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493460.0353684, "EndTime": 1750493460.1217542, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493459.8877323, "EndTime": 1750493460.126577, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493460.0344613, "EndTime": 1750493460.127323, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493460.121809, "EndTime": 1750493460.2094488, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493460.2095075, "EndTime": 1750493460.2916806, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493460.1273942, "EndTime": 1750493460.2941673, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493460.2945306, "EndTime": 1750493460.3295712, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493460.3297117, "EndTime": 1750493460.3554747, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750493460.2918, "EndTime": 1750493460.484852, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}

In [24]:
def parse_s3_uri(s3_uri):
    from urllib.parse import urlparse
    from pathlib import PurePosixPath
    
    parsed = urlparse(s3_uri)
    bucket = parsed.netloc
    key = parsed.path.lstrip('/')
    prefix_folder = '/'.join(key.split('/')[:-1]) if '/' in key else ''
    filename = PurePosixPath(key).name
    return bucket, prefix_folder, filename

# Example usage:
#s3_uri = 's3://my-bucket/folder1/folder2/file.txt'
#bucket, prefix, filename = parse_s3_uri(s3_uri)
#print(bucket)   # my-bucket
#print(prefix)   # folder1/folder2
#print(filename) # file.txt

def generate_manifest_file(s3_images_loc, s3_input_csv):
    # assumes s3 bucket access is available
    # creates a manifest file based on the input csv, and uploads it to the same s3 directory as the input_csv.
    # s3_images_loc is the common directory where all the images files are
    import os
    import pandas as pd
    import boto3
    from botocore.exceptions import ClientError
    
    df = pd.read_csv(s3_input_csv)
    manifest = [{"prefix": s3_images_loc}] + df['filename'].to_list()
    
    # parse s3uri of input csv
    bucket_name, prefix, filename = parse_s3_uri(s3_input_csv)

    # create manifest output name using the same filename as input
    output_filename = os.path.splitext(filename)[0] + ".manifest"
    
    s3_key = f"{prefix}/{output_filename}"
    
    # Write the manifest to a JSON file (for local, delete later)
    with open(output_filename, "w") as f:
        json.dump(manifest, f, indent=2)

    
    # upload manifest to s3 location same as input csv
    s3_client = boto3.client('s3')
    try:
        s3_client.upload_file(output_filename, bucket_name, s3_key)
        print(f"File uploaded to s3://{bucket_name}/{s3_key}")
    except ClientError as e:
        print(f"Error uploading file: {e}")

    # return manifest file's s3 prefix, and the full s3 path to the manifest object
    s3_prefix_manifest = f"s3://{bucket_name}/{prefix}/"
    s3_uri_manifest = s3_prefix_manifest + output_filename
    
    display(s3_prefix_manifest)
    display(s3_uri_manifest)
    
    return s3_prefix_manifest, s3_uri_manifest

In [18]:
# set input csv from s3 location
input_csv = "s3://aai-540-data/dev_split/validation/val-meta.csv"

# try generating manifest file
generate_manifest_file(s3_input_csv = input_csv, s3_images_loc = f"s3://{bucket_name}/cct_resized/")

'aai-540-data'

'dev_split/validation'

'val-meta.csv'

'val-meta.manifest'

'dev_split/validation/val-meta.manifest'

File uploaded to s3://aai-540-data/dev_split/validation/val-meta.manifest

In [8]:
input_csv

's3://aai-540-data/dev_split/validation/val-meta.csv'

In [19]:
#### TRY AGAIN on VALIDATION CSV AFTER HAVING CONVERTED IT TO MANIFEST FILE

s3_transform_manifest = "s3://aai-540-data/dev_split/validation/val-meta.manifest"

# location of predictions 
# should be automated, and should be a folder within where the manifest file is
s3_transform_out = "s3://aai-540-data/dev_split/validation/batch_transform_output/"

In [20]:
# try batch transform on validation set (with manifest file) but this time, create a json/csv table output
# load the model name to be used, must be in sagemaker
sagemaker_model_name = "image-classification-2025-06-19-16-11-57-811"

# initialize Tranformer
transformer2 = Transformer(
    model_name = sagemaker_model_name,
    instance_count=1,  # Number of instances
    instance_type="ml.g4dn.xlarge",  # Instance type
    output_path=s3_transform_out,  # Predictions output
    max_payload=10,  # Max payload size (MB)
    strategy="MultiRecord" ,
    max_concurrent_transforms=10,
    sagemaker_session=sess,

    accept = 'txt/csv', # so output is generated in single file
    assemble_with='Line', # new line is generated for each prediction
  
    #accept='application/json',
    
)

In [22]:
%%time

# batch transform images in manifest file
transformer2.transform(
    data=s3_transform_manifest,
    data_type='ManifestFile', # provide list of s3uris of objects to be batch transformed
    content_type='application/x-image', 
    split_type='None', # because each object is an image file to be processed, no splitting needed
    #accept = 'text/csv', # output file format
    logs=True,
    wait=True
)

INFO:sagemaker:Creating transform job with name: image-classification-2025-06-21-11-11-11-458

.................................Docker entrypoint called with argument(s): serve
Running default environment configuration script
Nvidia gpu devices, drivers and cuda toolkit versions (only available on hosts with GPU):
Sat Jun 21 11:16:42 2025
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.256.02   Driver Version: 470.256.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   30C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Checking for nvidia driver and cuda compatibility.
CUDA Compatibility driver provided.
Proceeding with compatibility check between driver, cuda-toolkit and cuda-compat.
Detected cuda-toolkit version: 11.1.
Detected cuda-compat version: 455.32.00.
Detected Nvidia driver version: 470.256.02.
Nvidia driver compatible with cuda-toolkit. Disabling cuda-compat.
/opt/amazon/lib/python3.8/site-packages/mxnet/model.py:97: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if num_device is 1 and 'dist' not in kvstore:
[06/21/2025 11:16:45 INFO 140528611772224] loaded entry point class algorithm.serve.server_config:config_api
[06/21/2025 11:16:45 INFO 140528611772224] loading entry points
[06/21/2025 11:16:45 INFO 140528611772224] loaded request iterator application/x-image
[06/21/2025 11:16:45 INFO 140528611772224] loaded request iterator image/jpeg
[06/21/2025 11:16:45 INFO 140528611772224] loaded request iterator image/png
[06/21/2025 11:16:45 INFO 140528611772224] loaded response encoder application/json
[06/21/2025 11:16:45 INFO 140528611772224] loaded response encoder application/jsonlines
[06/21/2025 11:16:45 INFO 140528611772224] loaded entry point class algorithm:model
[06/21/2025 11:16:45 INFO 140528611772224] Number of server workers: 3
[2025-06-21 11:16:45 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2025-06-21 11:16:45 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2025-06-21 11:16:45 +0000] [1] [INFO] Using worker: sync
[2025-06-21 11:16:45 +0000] [59] [INFO] Booting worker with pid: 59
[06/21/2025 11:16:45 INFO 140528611772224] loading model...
[06/21/2025 11:16:45 WARNING 140528611772224] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[2025-06-21 11:16:45 +0000] [68] [INFO] Booting worker with pid: 68
[06/21/2025 11:16:45 INFO 140528611772224] loading model...
[06/21/2025 11:16:45 WARNING 140528611772224] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[06/21/2025 11:16:45 INFO 140528611772224] nvidia-smi: took 0.036 seconds to run.
[06/21/2025 11:16:45 INFO 140528611772224] nvidia-smi identified 1 GPUs.
[06/21/2025 11:16:45 INFO 140528611772224] Number of GPUs being used: 1
[06/21/2025 11:16:45 INFO 140528611772224] Using device: 0 for worker PID: 59
[06/21/2025 11:16:45 INFO 140528611772224] Looking for model file in /opt/ml/model
[06/21/2025 11:16:45 INFO 140528611772224] Loading /opt/ml/model/image-classification-0009.params
[06/21/2025 11:16:45 INFO 140528611772224] nvidia-smi: took 0.030 seconds to run.
[06/21/2025 11:16:45 INFO 140528611772224] nvidia-smi identified 1 GPUs.
[06/21/2025 11:16:45 INFO 140528611772224] Number of GPUs being used: 1
[06/21/2025 11:16:45 INFO 140528611772224] Using device: 0 for worker PID: 68
[06/21/2025 11:16:45 INFO 140528611772224] Looking for model file in /opt/ml/model
[06/21/2025 11:16:45 INFO 140528611772224] Loading /opt/ml/model/image-classification-0009.params
[2025-06-21 11:16:45 +0000] [101] [INFO] Booting worker with pid: 101
[06/21/2025 11:16:45 INFO 140528611772224] loading model...
[06/21/2025 11:16:45 WARNING 140528611772224] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[06/21/2025 11:16:46 INFO 140528611772224] nvidia-smi: took 0.036 seconds to run.
[06/21/2025 11:16:46 INFO 140528611772224] nvidia-smi identified 1 GPUs.
[06/21/2025 11:16:46 INFO 140528611772224] Number of GPUs being used: 1
[06/21/2025 11:16:46 INFO 140528611772224] Using device: 0 for worker PID: 101
[06/21/2025 11:16:46 INFO 140528611772224] Looking for model file in /opt/ml/model
[06/21/2025 11:16:46 INFO 140528611772224] Loading /opt/ml/model/image-classification-0009.params
[06/21/2025 11:16:46 INFO 140528611772224] Using Context: gpu(0)
[06/21/2025 11:16:46 INFO 140528611772224] Using Context: gpu(0)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[06/21/2025 11:16:46 INFO 140528611772224] Using Context: gpu(0)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[06/21/2025 11:16:51 INFO 140528611772224] ...model loaded.
[06/21/2025 11:16:51 INFO 140528611772224] ...model loaded.
[06/21/2025 11:16:51 INFO 140528611772224] ...model loaded.
#metrics {"StartTime": 1750504611.512778, "EndTime": 1750504611.7560582, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"execution_parameters.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
[11:16:51] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[11:16:52] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[06/21/2025 11:16:51 INFO 140528611772224] ...model loaded.
[06/21/2025 11:16:51 INFO 140528611772224] ...model loaded.
[06/21/2025 11:16:51 INFO 140528611772224] ...model loaded.
#metrics {"StartTime": 1750504611.512778, "EndTime": 1750504611.7560582, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"execution_parameters.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
[11:16:51] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[11:16:52] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[11:16:52] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
#metrics {"StartTime": 1750504611.7562227, "EndTime": 1750504612.7260375, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
[11:16:52] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
#metrics {"StartTime": 1750504611.7562227, "EndTime": 1750504612.7260375, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504611.5373173, "EndTime": 1750504612.728274, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.7260964, "EndTime": 1750504612.7406886, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.7283492, "EndTime": 1750504612.7486157, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.7407503, "EndTime": 1750504612.7524476, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504611.6256666, "EndTime": 1750504612.754327, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.7525077, "EndTime": 1750504612.7639701, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.7544816, "EndTime": 1750504612.7658803, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.748682, "EndTime": 1750504612.7668762, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.7640452, "EndTime": 1750504612.7722368, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.7669358, "EndTime": 1750504612.9568124, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.7722752, "EndTime": 1750504613.0533812, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.956877, "EndTime": 1750504613.0534575, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.7659376, "EndTime": 1750504613.0583827, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504611.5373173, "EndTime": 1750504612.728274, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.7260964, "EndTime": 1750504612.7406886, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.7283492, "EndTime": 1750504612.7486157, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.7407503, "EndTime": 1750504612.7524476, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504611.6256666, "EndTime": 1750504612.754327, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.7525077, "EndTime": 1750504612.7639701, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.7544816, "EndTime": 1750504612.7658803, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.748682, "EndTime": 1750504612.7668762, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.7640452, "EndTime": 1750504612.7722368, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.7669358, "EndTime": 1750504612.9568124, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.7722752, "EndTime": 1750504613.0533812, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.956877, "EndTime": 1750504613.0534575, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504612.7659376, "EndTime": 1750504613.0583827, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504613.0534494, "EndTime": 1750504613.1015387, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504613.0584464, "EndTime": 1750504613.1020525, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504613.1021173, "EndTime": 1750504613.15262, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504613.0536578, "EndTime": 1750504613.2259605, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504613.1016018, "EndTime": 1750504613.2309947, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504613.1526773, "EndTime": 1750504613.2315574, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504613.23112, "EndTime": 1750504613.336651, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504613.2262967, "EndTime": 1750504613.3418963, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504613.0534494, "EndTime": 1750504613.1015387, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504613.0584464, "EndTime": 1750504613.1020525, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504613.1021173, "EndTime": 1750504613.15262, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504613.0536578, "EndTime": 1750504613.2259605, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504613.1016018, "EndTime": 1750504613.2309947, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504613.1526773, "EndTime": 1750504613.2315574, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750504613.23112, "EndTime": 1750504613.336651, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}

------

In [25]:
# try again the entire inference pipeline with dataProcessingConfig with join_source - input

# set input csv from s3 location
input_csv = "s3://aai-540-data/ground_truth/2012/5/labels.csv"
# try generating manifest file & get the prefix of the input csv
s3_transform_out, s3_transform_manifest = generate_manifest_file(s3_input_csv = input_csv, s3_images_loc = f"s3://{bucket_name}/cct_resized/")
s3_transform_out = s3_transform_out + "batch_transform_output/"

display(s3_transform_out, s3_transform_manifest)

'aai-540-data'

'ground_truth/2012/5'

'labels.csv'

'labels.manifest'

'ground_truth/2012/5/labels.manifest'

File uploaded to s3://aai-540-data/ground_truth/2012/5/labels.manifest

's3://aai-540-data/ground_truth/2012/5/'

's3://aai-540-data/ground_truth/2012/5/labels.manifest'

's3://aai-540-data/ground_truth/2012/5/batch_transform_output/'

's3://aai-540-data/ground_truth/2012/5/labels.manifest'

In [30]:
# try batch transform on validation set (with manifest file) but this time, create a json/csv table output
# load the model name to be used, must be in sagemaker
from sagemaker import DataProcessing
sagemaker_model_name = "image-classification-2025-06-19-16-11-57-811"

# initialize Tranformer
transformer3 = Transformer(
    model_name = sagemaker_model_name,
    instance_count=1,  # Number of instances
    instance_type="ml.g4dn.xlarge",  # Instance type
    output_path=s3_transform_out,  # Predictions output
    max_payload=10,  # Max payload size (MB)
    strategy="MultiRecord" ,
    max_concurrent_transforms=10,
    sagemaker_session=sess,

    accept = 'txt/csv', # so output is generated in single file
    assemble_with='Line', # new line is generated for each prediction

    
)

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:3                                                                                    │
│                                                                                                  │
│    1 # try batch transform on validation set (with manifest file) but this time, create a jso    │
│    2 # load the model name to be used, must be in sagemaker                                      │
│ ❱  3 from sagemaker import DataProcessing                                                        │
│    4 sagemaker_model_name = "image-classification-2025-06-19-16-11-57-811"                       │
│    5                                                                                             │
│    6 # initialize Tranformer                                                                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'DataProcessing' from 'sagemaker'
(/opt/conda/lib/python3.12/site-packages/sagemaker/__init__.py)

In [28]:
%%time

# batch transform images in manifest file
transformer3.transform(
    data=s3_transform_manifest,
    data_type='ManifestFile', # provide list of s3uris of objects to be batch transformed
    content_type='application/x-image', 
    split_type='None', # because each object is an image file to be processed, no splitting needed
    join_source = 'Input',
    logs=True,
    wait=True
)

INFO:sagemaker:Creating transform job with name: image-classification-2025-06-21-11-49-24-493

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /opt/conda/lib/python3.12/site-packages/IPython/core/magics/execution.py:1362 in time            │
│                                                                                                  │
│   1359 │   │   if mode == "eval":                                                                │
│   1360 │   │   │   st = clock2()                                                                 │
│   1361 │   │   │   try:                                                                          │
│ ❱ 1362 │   │   │   │   out = eval(code, glob, local_ns)                                          │
│   1363 │   │   │   except Exception:                                                             │
│   1364 │   │   │   │   self.shell.showtraceback()                                                │
│   1365 │   │   │   │   return                                                                    │
│ in <module>:2                                                                                    │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/workflow/pipeline_context.py:346 in wrapper    │
│                                                                                                  │
│   343 │   │   │                                                                                  │
│   344 │   │   │   return _StepArguments(retrieve_caller_name(self_instance), run_func, *args,    │
│   345 │   │                                                                                      │
│ ❱ 346 │   │   return run_func(*args, **kwargs)                                                   │
│   347 │                                                                                          │
│   348 │   return wrapper                                                                         │
│   349                                                                                            │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/transformer.py:302 in transform                │
│                                                                                                  │
│   299 │   │   │   sagemaker_session=self.sagemaker_session,                                      │
│   300 │   │   )                                                                                  │
│   301 │   │                                                                                      │
│ ❱ 302 │   │   self.latest_transform_job = _TransformJob.start_new(                               │
│   303 │   │   │   self,                                                                          │
│   304 │   │   │   data,                                                                          │
│   305 │   │   │   data_type,                                                                     │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/transformer.py:636 in start_new                │
│                                                                                                  │
│   633 │   │   │   batch_data_capture_config,                                                     │
│   634 │   │   )                                                                                  │
│   635 │   │                                                                                      │
│ ❱ 636 │   │   transformer.sagemaker_session.transform(**transform_args)                          │
│   637 │   │                                                                                      │
│   638 │   │   return cls(transformer.sagemaker_session, transformer._current_job_name)           │
│   639                                                                                            │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/session.py:3966 in transform                   │
│                                                                                                  │
│   3963 │   │   │   logger.debug("Transform request: %s", json.dumps(request, indent=4))          │
│   3964 │   │   │   self.sagemaker_client.create_transform_job(**request)                         │
│   3965 │   │                                                                                     │
│ ❱ 3966 │   │   self._intercept_create_request(transform_request, submit, self.transform.__name_  │
│   3967 │                                                                                         │
│   3968 │   def _create_model_request(                                                            │
│   3969 │   │   self,                                                                             │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/session.py:6819 in _intercept_create_request   │
│                                                                                                  │
│   6816 │   │   │   create (functor): a functor calls the sagemaker client create method          │
│   6817 │   │   │   func_name (str): the name of the function needed intercepting                 │
│   6818 │   │   """                                                                               │
│ ❱ 6819 │   │   return create(request)                                                            │
│   6820 │                                                                                         │
│   6821 │   def _create_inference_recommendations_job_request(                                    │
│   6822 │   │   self,                                                                             │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/session.py:3964 in submit                      │
│                                                                                                  │
│   3961 │   │   def submit(request):                                                              │
│   3962 │   │   │   logger.info("Creating transform job with name: %s", job_name)                 │
│   3963 │   │   │   logger.debug("Transform request: %s", json.dumps(request, indent=4))          │
│ ❱ 3964 │   │   │   self.sagemaker_client.create_transform_job(**request)                         │
│   3965 │   │                                                                                     │
│   3966 │   │   self._intercept_create_request(transform_request, submit, self.transform.__name_  │
│   3967                                                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/botocore/client.py:569 in _api_call                      │
│                                                                                                  │
│    566 │   │   │   │   │   f"{py_operation_name}() only accepts keyword arguments."              │
│    567 │   │   │   │   )                                                                         │
│    568 │   │   │   # The "self" in this scope is referring to the BaseClient.                    │
│ ❱  569 │   │   │   return self._make_api_call(operation_name, kwargs)                            │
│    570 │   │                                                                                     │
│    571 │   │   _api_call.__name__ = str(py_operation_name)                                       │
│    572                                                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/botocore/client.py:1023 in _make_api_call                │
│                                                                                                  │
│   1020 │   │   │   │   "Code"                                                                    │
│   1021 │   │   │   )                                                                             │
│   1022 │   │   │   error_class = self.exceptions.from_code(error_code)                           │
│ ❱ 1023 │   │   │   raise error_class(parsed_response, operation_name)                            │
│   1024 │   │   else:                                                                             │
│   1025 │   │   │   return parsed_response                                                        │
│   1026                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ClientError: An error occurred (ValidationException) when calling the CreateTransformJob operation: ContentType
("application/x-image") in TransformInput has to be the same as Accept ("txt/csv") in TransformOutput when
JoinSource is "Input".

In [29]:
transformer3.delete_model

In [31]:
s3_inferences_loc = s3_transform_out
bucket_name, prefix, filename = parse_s3_uri(s3_inferences_loc)

In [33]:
prefix

'ground_truth/2012/5/batch_transform_output'

In [34]:
# Post Processing Function after Batch Transform

# define function that collects all batch predictions within the transformer output folder location and generates a csv file with filename and pred probabilities per class
def combine_inferences_to_csv(s3_inferences_loc):
    # s3_inferences_loc is a full path to an s3 prefix where transform results are located
    # default output location of combined csv is....
    import boto3
    import os
    import pandas as pd

    s3 = boto3.client('s3')

    # 1. List all .out files using paginator (more than 1000 objects)
    paginator = s3.get_paginator('list_objects_v2')
    out_files = []
    bucket_name, prefix, filename = parse_s3_uri(s3_inferences_loc)
    for page in paginator.paginate(Bucket=bucket_name, Prefix=prefix):
        for obj in page.get('Contents', []):
            if obj['Key'].endswith('.out'):
                out_files.append(obj['Key'])

    # 2. Download and collect filename (without .out) and contents
    merged_lines = []
    for key in out_files:
        response = s3.get_object(Bucket=bucket_name, Key=key)
        body = response['Body'].read().decode('utf-8')
        filename_with_ext = key.split('/')[-1]
        filename_no_ext = os.path.splitext(filename_with_ext)[0]  # Removes .out
        merged_lines.append(json.dumps({'filename': filename_no_ext, 'content': body}))

    # 3. Join all JSON objects as lines (JSONLines format)
    final_content = '\n'.join(merged_lines)

    # 4. Save merged content to a local file
    merged_filename = './tmp/merged_inferences.json'
    with open(merged_filename, 'w') as f:
        f.write(final_content)


    # Write the manifest to a JSON file (for local, delete later)
    #with open(output_filename, "w") as f:
    #    json.dump(manifest, f, indent=2)

In [35]:
s3_transform_out = "s3://aai-540-data/dev_split/validation/batch_transform_output/"
s3_inferences_loc = s3_transform_out
combine_inferences_to_csv(s3_inferences_loc)

In [36]:
tmp_df = pd.read_json("s3://aai-540-data/dev_split/validation/batch_transform_output/5858bf67-23d2-11e8-a6a3-ec086b02610b_0.jpg.out")

In [37]:
tmp_df

      prediction
0   4.962599e-04
1   1.252794e-07
2   1.848768e-04
3   9.791388e-06
4   3.618970e-06
5   1.035538e-05
6   6.905704e-08
7   2.959790e-05
8   8.348932e-06
9   6.160833e-06
10  1.095342e-06
11  1.405219e-06
12  1.193723e-05
13  9.992275e-01
14  8.560716e-06
15  2.285140e-07
16  5.319324e-08

In [50]:
tmp_df = pd.read_json("s3://aai-540-data/dev_split/validation/batch_transform_output/5858bf67-23d2-11e8-a6a3-ec086b02610b_0.jpg.out")

In [53]:
tmp_df['prediction'].to_list()

[0.000496259948704,
 1.252793850881062e-07,
 0.000184876815183,
 9.791388038138393e-06,
 3.618970367824658e-06,
 1.0355376616644202e-05,
 6.905704452719874e-08,
 2.9597900720546025e-05,
 8.348932169610634e-06,
 6.160833436297253e-06,
 1.095342213375261e-06,
 1.405219222760934e-06,
 1.19372334665968e-05,
 0.99922752380371,
 8.560716196370777e-06,
 2.285140254798534e-07,
 5.319323648222962e-08]

In [61]:
s3_input_csv = "s3://aai-540-data/dev_split/validation/val-meta.csv"
s3_transform_out = "s3://aai-540-data/dev_split/validation/batch_transform_output/"
s3_inferences_loc = s3_transform_out

In [88]:
# use pandas to merge the individual pred-probs file output of batch transform with the csv input of that folder

# define function that collects all batch predictions within the transformer output folder location and generates a csv file with filename and pred probabilities per class
def merge_inferences_with_input_csv(s3_input_csv, s3_inferences_loc):
    import pandas as pd
    import numpy as np
    import boto3

    # s3_inferences_loc is a full path to an s3 prefix where transform results are located
    # default output location of combined csv is....
    
    def get_pred_probs(row):
        # generate s3uri inference output based on the input filename
        s3_inference_path = s3_inferences_loc + row['filename'] + ".out"
        pred_probs_df = pd.read_json(s3_inference_path)

        return pred_probs_df['prediction'].to_list()

    # read input csv with filenames and true labels
    df = pd.read_csv(s3_input_csv)

    # get pred probs for each filename within the inferencees folder and add columns to new df
    df['pred_probs'] = df.apply(get_pred_probs, axis = 1)
    df['pred_label_enc'] = df['pred_probs'].apply(lambda x: x.index(max(x)))
    df['pred_label'] = df['pred_label_enc'].map(CURRENT_LABEL_MAP_INV)

    # save final df to local first
    output_filename = "merged_inferences.csv"
    df.to_csv(output_filename)
    df.to_csv("./tmp/merged_inferences2.csv")

    # upload merged csv to same s3 loc
    # parse s3uri of input csv
    bucket_name, prefix, filename = parse_s3_uri(s3_input_csv)
    display(bucket_name, prefix, filename)

    s3_key = f"{prefix}/{output_filename}"
    display(output_filename, s3_key)

    # upload merged df to same s3 location same as input csv
    s3_client = boto3.client('s3')
    try:
        s3_client.upload_file(output_filename, bucket_name, s3_key)
        print(f"File uploaded to s3://{bucket_name}/{s3_key}")
    except ClientError as e:
        print(f"Error uploading file: {e}")

In [63]:
%%time
merge_inferences_with_input_csv(s3_input_csv, s3_inferences_loc)

CPU times: user 50.5 s, sys: 2.48 s, total: 53 s
Wall time: 8min 58s

In [121]:
# add to merge function later

# read label enc mapping that was used during tRAINING
CURRENT_LABEL_MAP = {'cat': 0,
 'opossum': 1,
 'squirrel': 2,
 'raccoon': 3,
 'bird': 4,
 'rabbit': 5,
 'dog': 6,
 'badger': 7,
 'bobcat': 8,
 'coyote': 9,
 'car': 10,
 'deer': 11,
 'rodent': 12,
 'skunk': 13,
 'empty': 14}

# Save mapping to JSON
with open('label_mapping.json', 'w') as f:
    json.dump(CURRENT_LABEL_MAP, f)

# create inverse map
CURRENT_LABEL_MAP_INV = {v: k for k, v in CURRENT_LABEL_MAP.items()}

In [85]:
CURRENT_LABEL_MAP_INV

{0: 'cat',
 1: 'opossum',
 2: 'squirrel',
 3: 'raccoon',
 4: 'bird',
 5: 'rabbit',
 6: 'dog',
 7: 'badger',
 8: 'bobcat',
 9: 'coyote',
 10: 'car',
 11: 'deer',
 12: 'rodent',
 13: 'skunk',
 14: 'empty'}

In [73]:
merged_df['pred_label'].value_counts()

pred_label
opossum     1690
raccoon     1068
coyote       639
cat          555
bobcat       488
car          424
dog          332
rabbit       314
squirrel     220
skunk        176
rodent        66
bird          59
empty         13
deer           4
Name: count, dtype: int64

In [116]:
from sklearn.metrics import classification_report

# generate classification metrics based on label_enc for now
report = classification_report(merged_df['label'], merged_df['pred_label'])

print(report)

              precision    recall  f1-score   support

        bird       0.95      0.63      0.76       807
      bobcat       0.05      0.50      0.09        12
         cat       0.00      0.00      0.00         0
      coyote       0.12      0.68      0.21       152
        deer       1.00      0.07      0.12      1226
         dog       0.00      0.00      0.00         0
       empty       0.00      0.00      0.00         8
         fox       0.00      0.00      0.00        12
      insect       0.00      0.00      0.00         6
      lizard       0.00      0.00      0.00        16
     opossum       0.00      0.00      0.00         0
      rabbit       0.74      0.78      0.76       159
     raccoon       0.03      0.75      0.06         4
      rodent       0.82      0.73      0.77        37
       skunk       0.44      0.57      0.50         7
    squirrel       0.00      0.00      0.00         0

    accuracy                           0.35      2446
   macro avg       0.26      0.29      0.20      2446
weighted avg       0.88      0.35      0.39      2446

/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [79]:
transformer3.delete_model()

INFO:sagemaker:Deleting model with name: image-classification-2025-06-19-16-11-57-811

In [82]:
### try all of the above on one ground truth month
# try again the entire inference pipeline with dataProcessingConfig with join_source - input

####### LOAD THE IMAGE CLASSIFIER MODEL #########
# if via Sagemaker, then no need to specify base image_uri
# otherwise, model.tar.gz required and base image_uri

# load the model name to be used, must be in sagemaker
sagemaker_model_name = "image-classification-2025-06-19-18-37-41-534" # workaround... register fine-tuned model on sagemaker then access from there

# set input csv from s3 location
input_csv = "s3://aai-540-data/ground_truth/2012/5/labels.csv"

# generating manifest file & get the prefix of the input csv
s3_transform_out, s3_transform_manifest = generate_manifest_file(s3_input_csv = input_csv, s3_images_loc = f"s3://aai-540-data/cct_resized/")
s3_transform_out = s3_transform_out + "batch_transform_output/"

display(s3_transform_out, s3_transform_manifest)

# initialize Tranformer
transformer3 = Transformer(
    model_name = sagemaker_model_name,
    instance_count=1,  # Number of instances
    instance_type="ml.g4dn.xlarge",  # Instance type
    output_path=s3_transform_out,  # Predictions output
    max_payload=10,  # Max payload size (MB)
    strategy="MultiRecord" ,
    max_concurrent_transforms=10,
    sagemaker_session=sess,

    accept = 'txt/csv', # so output is generated in single file
    assemble_with='Line', # new line is generated for each prediction

)

'aai-540-data'

'ground_truth/2012/5'

'labels.csv'

'labels.manifest'

'ground_truth/2012/5/labels.manifest'

File uploaded to s3://aai-540-data/ground_truth/2012/5/labels.manifest

's3://aai-540-data/ground_truth/2012/5/'

's3://aai-540-data/ground_truth/2012/5/labels.manifest'

's3://aai-540-data/ground_truth/2012/5/batch_transform_output/'

's3://aai-540-data/ground_truth/2012/5/labels.manifest'

In [83]:
%%time

# batch transform images in manifest file
transformer3.transform(
    data=s3_transform_manifest,
    data_type='ManifestFile', # provide list of s3uris of objects to be batch transformed
    content_type='application/x-image', 
    split_type='None', # because each object is an image file to be processed, no splitting needed
    #accept = 'text/csv', # output file format
    logs=True,
    wait=True
)

INFO:sagemaker:Creating transform job with name: image-classification-2025-06-21-15-31-20-723

............................Docker entrypoint called with argument(s): serve
Running default environment configuration script
Nvidia gpu devices, drivers and cuda toolkit versions (only available on hosts with GPU):
Sat Jun 21 15:36:02 2025
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.256.02   Driver Version: 470.256.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   35C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Checking for nvidia driver and cuda compatibility.
CUDA Compatibility driver provided.
Proceeding with compatibility check between driver, cuda-toolkit and cuda-compat.
Detected cuda-toolkit version: 11.1.
Detected cuda-compat version: 455.32.00.
Detected Nvidia driver version: 470.256.02.
Nvidia driver compatible with cuda-toolkit. Disabling cuda-compat.
/opt/amazon/lib/python3.8/site-packages/mxnet/model.py:97: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if num_device is 1 and 'dist' not in kvstore:
[06/21/2025 15:36:05 INFO 140158132229952] loaded entry point class algorithm.serve.server_config:config_api
[06/21/2025 15:36:05 INFO 140158132229952] loading entry points
[06/21/2025 15:36:05 INFO 140158132229952] loaded request iterator application/x-image
[06/21/2025 15:36:05 INFO 140158132229952] loaded request iterator image/jpeg
[06/21/2025 15:36:05 INFO 140158132229952] loaded request iterator image/png
[06/21/2025 15:36:05 INFO 140158132229952] loaded response encoder application/json
[06/21/2025 15:36:05 INFO 140158132229952] loaded response encoder application/jsonlines
[06/21/2025 15:36:05 INFO 140158132229952] loaded entry point class algorithm:model
[06/21/2025 15:36:05 INFO 140158132229952] Number of server workers: 3
[2025-06-21 15:36:05 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2025-06-21 15:36:05 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2025-06-21 15:36:05 +0000] [1] [INFO] Using worker: sync
[2025-06-21 15:36:05 +0000] [60] [INFO] Booting worker with pid: 60
[06/21/2025 15:36:05 INFO 140158132229952] loading model...
[06/21/2025 15:36:05 WARNING 140158132229952] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[06/21/2025 15:36:05 INFO 140158132229952] nvidia-smi: took 0.033 seconds to run.
[06/21/2025 15:36:05 INFO 140158132229952] nvidia-smi identified 1 GPUs.
[06/21/2025 15:36:05 INFO 140158132229952] Number of GPUs being used: 1
[06/21/2025 15:36:05 INFO 140158132229952] Using device: 0 for worker PID: 60
[06/21/2025 15:36:05 INFO 140158132229952] Looking for model file in /opt/ml/model
[06/21/2025 15:36:05 INFO 140158132229952] Loading /opt/ml/model/image-classification-0009.params
[06/21/2025 15:36:05 INFO 140158132229952] Using Context: gpu(0)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[2025-06-21 15:36:05 +0000] [81] [INFO] Booting worker with pid: 81
[06/21/2025 15:36:05 INFO 140158132229952] loading model...
[06/21/2025 15:36:05 WARNING 140158132229952] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[06/21/2025 15:36:05 INFO 140158132229952] nvidia-smi: took 0.032 seconds to run.
[06/21/2025 15:36:05 INFO 140158132229952] nvidia-smi identified 1 GPUs.
[06/21/2025 15:36:05 INFO 140158132229952] Number of GPUs being used: 1
[06/21/2025 15:36:05 INFO 140158132229952] Using device: 0 for worker PID: 81
[06/21/2025 15:36:05 INFO 140158132229952] Looking for model file in /opt/ml/model
[06/21/2025 15:36:05 INFO 140158132229952] Loading /opt/ml/model/image-classification-0009.params
[2025-06-21 15:36:05 +0000] [102] [INFO] Booting worker with pid: 102
[06/21/2025 15:36:05 INFO 140158132229952] Using Context: gpu(0)
[06/21/2025 15:36:05 INFO 140158132229952] loading model...
[06/21/2025 15:36:05 WARNING 140158132229952] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[06/21/2025 15:36:05 INFO 140158132229952] nvidia-smi: took 0.038 seconds to run.
[06/21/2025 15:36:05 INFO 140158132229952] nvidia-smi identified 1 GPUs.
[06/21/2025 15:36:05 INFO 140158132229952] Number of GPUs being used: 1
[06/21/2025 15:36:05 INFO 140158132229952] Using device: 0 for worker PID: 102
[06/21/2025 15:36:05 INFO 140158132229952] Looking for model file in /opt/ml/model
[06/21/2025 15:36:05 INFO 140158132229952] Loading /opt/ml/model/image-classification-0009.params
[06/21/2025 15:36:05 INFO 140158132229952] Using Context: gpu(0)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[06/21/2025 15:36:10 INFO 140158132229952] ...model loaded.
[06/21/2025 15:36:10 INFO 140158132229952] ...model loaded.
[06/21/2025 15:36:10 INFO 140158132229952] ...model loaded.
#metrics {"StartTime": 1750520170.9029868, "EndTime": 1750520171.2152305, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"execution_parameters.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
[06/21/2025 15:36:10 INFO 140158132229952] ...model loaded.
[06/21/2025 15:36:10 INFO 140158132229952] ...model loaded.
[06/21/2025 15:36:10 INFO 140158132229952] ...model loaded.
#metrics {"StartTime": 1750520170.9029868, "EndTime": 1750520171.2152305, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"execution_parameters.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
[15:36:11] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[15:36:11] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[15:36:11] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
#metrics {"StartTime": 1750520170.9649043, "EndTime": 1750520172.1324258, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.1324968, "EndTime": 1750520172.1436954, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.143846, "EndTime": 1750520172.1559062, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.1560543, "EndTime": 1750520172.1694398, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.169839, "EndTime": 1750520172.1801193, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.1801617, "EndTime": 1750520172.1892526, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.1892943, "EndTime": 1750520172.199368, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520170.9389746, "EndTime": 1750520172.200328, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520171.2153177, "EndTime": 1750520172.2052743, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.1994252, "EndTime": 1750520172.210943, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
[15:36:11] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[15:36:11] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[15:36:11] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
#metrics {"StartTime": 1750520170.9649043, "EndTime": 1750520172.1324258, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.1324968, "EndTime": 1750520172.1436954, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.143846, "EndTime": 1750520172.1559062, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.1560543, "EndTime": 1750520172.1694398, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.169839, "EndTime": 1750520172.1801193, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.1801617, "EndTime": 1750520172.1892526, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.1892943, "EndTime": 1750520172.199368, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520170.9389746, "EndTime": 1750520172.200328, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520171.2153177, "EndTime": 1750520172.2052743, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.1994252, "EndTime": 1750520172.210943, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.2109838, "EndTime": 1750520172.324534, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.205343, "EndTime": 1750520172.3253381, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.325625, "EndTime": 1750520172.4407487, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.200405, "EndTime": 1750520172.4475322, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.3246386, "EndTime": 1750520172.5548058, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.4475944, "EndTime": 1750520172.5583713, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.5551457, "EndTime": 1750520172.592701, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.5930417, "EndTime": 1750520172.6085749, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.6086183, "EndTime": 1750520172.6270144, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.5584338, "EndTime": 1750520172.6271415, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.6271834, "EndTime": 1750520172.7423544, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.4408202, "EndTime": 1750520172.748467, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.6270728, "EndTime": 1750520172.7612119, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.7487578, "EndTime": 1750520172.7635841, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.7424343, "EndTime": 1750520172.7685688, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.2109838, "EndTime": 1750520172.324534, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.205343, "EndTime": 1750520172.3253381, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.325625, "EndTime": 1750520172.4407487, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.200405, "EndTime": 1750520172.4475322, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.3246386, "EndTime": 1750520172.5548058, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.4475944, "EndTime": 1750520172.5583713, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.5551457, "EndTime": 1750520172.592701, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750520172.5930417, "EndTime": 1750520172.6085749, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}

In [90]:
%%time
merge_inferences_with_input_csv(s3_input_csv = input_csv, s3_inferences_loc = s3_transform_out)

'aai-540-data'

'ground_truth/2012/5'

'labels.csv'

'merged_inferences.csv'

'ground_truth/2012/5/merged_inferences.csv'

File uploaded to s3://aai-540-data/ground_truth/2012/5/merged_inferences.csv
CPU times: user 34.5 s, sys: 1.51 s, total: 36 s
Wall time: 5min 52s

In [92]:
# remove later and update how csv files are generated for each ground truth month
labels_tmp_df = pd.read_csv("./tmp/labels.csv")
labels_tmp_df = labels_tmp_df[['filename','label']]
labels_tmp_df

                                        filename    label
0     59830994-23d2-11e8-a6a3-ec086b02610b_0.jpg  opossum
1     59f12a76-23d2-11e8-a6a3-ec086b02610b_0.jpg  opossum
2     59e77e94-23d2-11e8-a6a3-ec086b02610b_0.jpg  opossum
3     593d6a1f-23d2-11e8-a6a3-ec086b02610b_0.jpg   coyote
4     5874d51b-23d2-11e8-a6a3-ec086b02610b_0.jpg   coyote
...                                          ...      ...
4020  5a1caf7e-23d2-11e8-a6a3-ec086b02610b_0.jpg  opossum
4021  5a0b0038-23d2-11e8-a6a3-ec086b02610b_0.jpg  opossum
4022  5860ee63-23d2-11e8-a6a3-ec086b02610b_0.jpg  opossum
4023  58732daa-23d2-11e8-a6a3-ec086b02610b_0.jpg  opossum
4024  59104947-23d2-11e8-a6a3-ec086b02610b_0.jpg  opossum

[4025 rows x 2 columns]

In [93]:
merged_df = pd.read_csv("s3://aai-540-data/ground_truth/2012/5/merged_inferences.csv")
merged_df = pd.merge(merged_df, labels_tmp_df, on='filename')
merged_df.head()

,Unnamed: 0,label_enc,filename,date_captured,timestamp,pred_probs,pred_label_enc,pred_label,label
0,0,1.0,59830994-23d2-11e8-a6a3-ec086b02610b_0.jpg,2012-05-01 01:01:22,2012-05-01 01:01:22,"[2.6269816298673823e-15, 1.0, 2.55084289702987...",1,opossum,opossum
1,1,1.0,59f12a76-23d2-11e8-a6a3-ec086b02610b_0.jpg,2012-05-01 01:01:23,2012-05-01 01:01:23,"[7.655614098212027e-08, 0.9999608993530271, 2....",1,opossum,opossum
2,2,1.0,59e77e94-23d2-11e8-a6a3-ec086b02610b_0.jpg,2012-05-01 01:01:24,2012-05-01 01:01:24,"[5.83206920257151e-12, 0.9999998807907101, 2.4...",1,opossum,opossum
3,3,9.0,593d6a1f-23d2-11e8-a6a3-ec086b02610b_0.jpg,2012-05-01 04:27:31,2012-05-01 04:27:31,"[1.9697476091096174e-05, 5.29605358678964e-07,...",9,coyote,coyote
4,4,9.0,5874d51b-23d2-11e8-a6a3-ec086b02610b_0.jpg,2012-05-01 04:27:32,2012-05-01 04:27:32,"[0.001397736719809, 0.001132166711613, 0.00012...",9,coyote,coyote

In [94]:
# show classification report on merged data
# read merged csv from s3

# generate classification metrics based on label_enc for now
report = classification_report(merged_df['label'], merged_df['pred_label'])

print(report)

              precision    recall  f1-score   support

        bird       0.08      0.65      0.14        17
      bobcat       0.78      0.81      0.79       358
         cat       0.80      0.63      0.70      1056
      coyote       0.76      0.74      0.75       363
         dog       0.56      0.75      0.65       122
       empty       0.00      0.00      0.00         1
         fox       0.00      0.00      0.00         1
     opossum       0.99      0.87      0.92      1128
      rabbit       0.88      0.94      0.90       381
     raccoon       0.85      0.89      0.87       419
      rodent       0.00      0.00      0.00         7
       skunk       0.56      0.83      0.67         6
    squirrel       0.46      0.84      0.60       166

    accuracy                           0.79      4025
   macro avg       0.52      0.61      0.54      4025
weighted avg       0.83      0.79      0.80      4025

/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [95]:
# try on 05-2014

# load the model name to be used, must be in sagemaker
sagemaker_model_name = "image-classification-2025-06-19-18-37-41-534" # workaround... register fine-tuned model on sagemaker then access from there

# set input csv from s3 location
input_csv = "s3://aai-540-data/ground_truth/2014/5/labels.csv"

# generating manifest file & get the prefix of the input csv
s3_transform_out, s3_transform_manifest = generate_manifest_file(s3_input_csv = input_csv, s3_images_loc = f"s3://aai-540-data/cct_resized/")
s3_transform_out = s3_transform_out + "batch_transform_output/"

display(s3_transform_out, s3_transform_manifest)

# initialize Tranformer
transformer4 = Transformer(
    model_name = sagemaker_model_name,
    instance_count=1,  # Number of instances
    instance_type="ml.g4dn.xlarge",  # Instance type
    output_path=s3_transform_out,  # Predictions output
    max_payload=10,  # Max payload size (MB)
    strategy="MultiRecord" ,
    max_concurrent_transforms=10,
    sagemaker_session=sess,

    accept = 'txt/csv', # so output is generated in single file
    assemble_with='Line', # new line is generated for each prediction

)

'aai-540-data'

'ground_truth/2014/5'

'labels.csv'

'labels.manifest'

'ground_truth/2014/5/labels.manifest'

File uploaded to s3://aai-540-data/ground_truth/2014/5/labels.manifest

's3://aai-540-data/ground_truth/2014/5/'

's3://aai-540-data/ground_truth/2014/5/labels.manifest'

's3://aai-540-data/ground_truth/2014/5/batch_transform_output/'

's3://aai-540-data/ground_truth/2014/5/labels.manifest'

In [96]:
%%time
# batch transform images in manifest file
transformer4.transform(
    data=s3_transform_manifest,
    data_type='ManifestFile', # provide list of s3uris of objects to be batch transformed
    content_type='application/x-image', 
    split_type='None', # because each object is an image file to be processed, no splitting needed
    #accept = 'text/csv', # output file format
    logs=True,
    wait=True
)

INFO:sagemaker:Creating transform job with name: image-classification-2025-06-21-17-05-31-382

......................................Docker entrypoint called with argument(s): serve
Running default environment configuration script
Nvidia gpu devices, drivers and cuda toolkit versions (only available on hosts with GPU):
Sat Jun 21 17:11:47 2025
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.256.02   Driver Version: 470.256.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
Docker entrypoint called with argument(s): serve
Running default environment configuration script
Nvidia gpu devices, drivers and cuda toolkit versions (only available on hosts with GPU):
Sat Jun 21 17:11:47 2025
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.256.02   Driver Version: 470.256.02   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   35C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Checking for nvidia driver and cuda compatibility.
CUDA Compatibility driver provided.
Proceeding with compatibility check between driver, cuda-toolkit and cuda-compat.
Detected cuda-toolkit version: 11.1.
Detected cuda-compat version: 455.32.00.
Detected Nvidia driver version: 470.256.02.
Nvidia driver compatible with cuda-toolkit. Disabling cuda-compat.
/opt/amazon/lib/python3.8/site-packages/mxnet/model.py:97: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if num_device is 1 and 'dist' not in kvstore:
[06/21/2025 17:11:51 INFO 140148613822272] loaded entry point class algorithm.serve.server_config:config_api
[06/21/2025 17:11:51 INFO 140148613822272] loading entry points
[06/21/2025 17:11:51 INFO 140148613822272] loaded request iterator application/x-image
[06/21/2025 17:11:51 INFO 140148613822272] loaded request iterator image/jpeg
[06/21/2025 17:11:51 INFO 140148613822272] loaded request iterator image/png
[06/21/2025 17:11:51 INFO 140148613822272] loaded response encoder application/json
[06/21/2025 17:11:51 INFO 140148613822272] loaded response encoder application/jsonlines
[06/21/2025 17:11:51 INFO 140148613822272] loaded entry point class algorithm:model
[06/21/2025 17:11:51 INFO 140148613822272] Number of server workers: 3
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   35C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Checking for nvidia driver and cuda compatibility.
CUDA Compatibility driver provided.
Proceeding with compatibility check between driver, cuda-toolkit and cuda-compat.
Detected cuda-toolkit version: 11.1.
Detected cuda-compat version: 455.32.00.
Detected Nvidia driver version: 470.256.02.
Nvidia driver compatible with cuda-toolkit. Disabling cuda-compat.
/opt/amazon/lib/python3.8/site-packages/mxnet/model.py:97: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if num_device is 1 and 'dist' not in kvstore:
[06/21/2025 17:11:51 INFO 140148613822272] loaded entry point class algorithm.serve.server_config:config_api
[06/21/2025 17:11:51 INFO 140148613822272] loading entry points
[06/21/2025 17:11:51 INFO 140148613822272] loaded request iterator application/x-image
[06/21/2025 17:11:51 INFO 140148613822272] loaded request iterator image/jpeg
[06/21/2025 17:11:51 INFO 140148613822272] loaded request iterator image/png
[06/21/2025 17:11:51 INFO 140148613822272] loaded response encoder application/json
[06/21/2025 17:11:51 INFO 140148613822272] loaded response encoder application/jsonlines
[06/21/2025 17:11:51 INFO 140148613822272] loaded entry point class algorithm:model
[06/21/2025 17:11:51 INFO 140148613822272] Number of server workers: 3
[2025-06-21 17:11:51 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2025-06-21 17:11:51 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2025-06-21 17:11:51 +0000] [1] [INFO] Using worker: sync
[2025-06-21 17:11:51 +0000] [60] [INFO] Booting worker with pid: 60
[06/21/2025 17:11:51 INFO 140148613822272] loading model...
[06/21/2025 17:11:51 WARNING 140148613822272] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[2025-06-21 17:11:51 +0000] [81] [INFO] Booting worker with pid: 81
[06/21/2025 17:11:51 INFO 140148613822272] loading model...
[06/21/2025 17:11:51 WARNING 140148613822272] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[06/21/2025 17:11:51 INFO 140148613822272] nvidia-smi: took 0.035 seconds to run.
[06/21/2025 17:11:51 INFO 140148613822272] nvidia-smi identified 1 GPUs.
[06/21/2025 17:11:51 INFO 140148613822272] Number of GPUs being used: 1
[06/21/2025 17:11:51 INFO 140148613822272] Using device: 0 for worker PID: 60
[06/21/2025 17:11:51 INFO 140148613822272] Looking for model file in /opt/ml/model
[06/21/2025 17:11:51 INFO 140148613822272] Loading /opt/ml/model/image-classification-0009.params
[2025-06-21 17:11:51 +0000] [102] [INFO] Booting worker with pid: 102
[06/21/2025 17:11:51 INFO 140148613822272] loading model...
[06/21/2025 17:11:51 WARNING 140148613822272] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[06/21/2025 17:11:51 INFO 140148613822272] nvidia-smi: took 0.036 seconds to run.
[06/21/2025 17:11:51 INFO 140148613822272] nvidia-smi identified 1 GPUs.
[06/21/2025 17:11:51 INFO 140148613822272] Number of GPUs being used: 1
[06/21/2025 17:11:51 INFO 140148613822272] Using device: 0 for worker PID: 81
[06/21/2025 17:11:51 INFO 140148613822272] Looking for model file in /opt/ml/model
[06/21/2025 17:11:51 INFO 140148613822272] Loading /opt/ml/model/image-classification-0009.params
[06/21/2025 17:11:51 INFO 140148613822272] Using Context: gpu(0)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[2025-06-21 17:11:51 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2025-06-21 17:11:51 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2025-06-21 17:11:51 +0000] [1] [INFO] Using worker: sync
[2025-06-21 17:11:51 +0000] [60] [INFO] Booting worker with pid: 60
[06/21/2025 17:11:51 INFO 140148613822272] loading model...
[06/21/2025 17:11:51 WARNING 140148613822272] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[2025-06-21 17:11:51 +0000] [81] [INFO] Booting worker with pid: 81
[06/21/2025 17:11:51 INFO 140148613822272] loading model...
[06/21/2025 17:11:51 WARNING 140148613822272] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[06/21/2025 17:11:51 INFO 140148613822272] nvidia-smi: took 0.035 seconds to run.
[06/21/2025 17:11:51 INFO 140148613822272] nvidia-smi identified 1 GPUs.
[06/21/2025 17:11:51 INFO 140148613822272] Number of GPUs being used: 1
[06/21/2025 17:11:51 INFO 140148613822272] Using device: 0 for worker PID: 60
[06/21/2025 17:11:51 INFO 140148613822272] Looking for model file in /opt/ml/model
[06/21/2025 17:11:51 INFO 140148613822272] Loading /opt/ml/model/image-classification-0009.params
[2025-06-21 17:11:51 +0000] [102] [INFO] Booting worker with pid: 102
[06/21/2025 17:11:51 INFO 140148613822272] loading model...
[06/21/2025 17:11:51 WARNING 140148613822272] Requesting context without setting the requested num of gpus. Using 'auto'
/opt/amazon/python3.8/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
[06/21/2025 17:11:51 INFO 140148613822272] nvidia-smi: took 0.036 seconds to run.
[06/21/2025 17:11:51 INFO 140148613822272] nvidia-smi identified 1 GPUs.
[06/21/2025 17:11:51 INFO 140148613822272] Number of GPUs being used: 1
[06/21/2025 17:11:51 INFO 140148613822272] Using device: 0 for worker PID: 81
[06/21/2025 17:11:51 INFO 140148613822272] Looking for model file in /opt/ml/model
[06/21/2025 17:11:51 INFO 140148613822272] Loading /opt/ml/model/image-classification-0009.params
[06/21/2025 17:11:51 INFO 140148613822272] Using Context: gpu(0)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[06/21/2025 17:11:51 INFO 140148613822272] nvidia-smi: took 0.046 seconds to run.
[06/21/2025 17:11:51 INFO 140148613822272] nvidia-smi identified 1 GPUs.
[06/21/2025 17:11:51 INFO 140148613822272] Number of GPUs being used: 1
[06/21/2025 17:11:51 INFO 140148613822272] Using device: 0 for worker PID: 102
[06/21/2025 17:11:51 INFO 140148613822272] Looking for model file in /opt/ml/model
[06/21/2025 17:11:51 INFO 140148613822272] Loading /opt/ml/model/image-classification-0009.params
[06/21/2025 17:11:51 INFO 140148613822272] Using Context: gpu(0)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[06/21/2025 17:11:51 INFO 140148613822272] Using Context: gpu(0)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[06/21/2025 17:11:51 INFO 140148613822272] nvidia-smi: took 0.046 seconds to run.
[06/21/2025 17:11:51 INFO 140148613822272] nvidia-smi identified 1 GPUs.
[06/21/2025 17:11:51 INFO 140148613822272] Number of GPUs being used: 1
[06/21/2025 17:11:51 INFO 140148613822272] Using device: 0 for worker PID: 102
[06/21/2025 17:11:51 INFO 140148613822272] Looking for model file in /opt/ml/model
[06/21/2025 17:11:51 INFO 140148613822272] Loading /opt/ml/model/image-classification-0009.params
[06/21/2025 17:11:51 INFO 140148613822272] Using Context: gpu(0)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[06/21/2025 17:11:51 INFO 140148613822272] Using Context: gpu(0)
/opt/amazon/lib/python3.8/site-packages/mxnet/module/base_module.py:68: UserWarning: Data provided by label_shapes don't match names specified by label_names ([] vs. ['softmax_label'])
  warnings.warn(msg)
[06/21/2025 17:11:56 INFO 140148613822272] ...model loaded.
[06/21/2025 17:11:56 INFO 140148613822272] ...model loaded.
#metrics {"StartTime": 1750525916.9582086, "EndTime": 1750525916.998046, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"execution_parameters.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
[06/21/2025 17:11:57 INFO 140148613822272] ...model loaded.
[06/21/2025 17:11:56 INFO 140148613822272] ...model loaded.
[06/21/2025 17:11:56 INFO 140148613822272] ...model loaded.
#metrics {"StartTime": 1750525916.9582086, "EndTime": 1750525916.998046, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"execution_parameters.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
[06/21/2025 17:11:57 INFO 140148613822272] ...model loaded.
2025-06-21T17:11:57.030:[sagemaker logs]: MaxConcurrentTransforms=10, MaxPayloadInMB=10, BatchStrategy=MULTI_RECORD
[17:11:57] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[17:11:57] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[17:11:57] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
#metrics {"StartTime": 1750525916.9981732, "EndTime": 1750525917.8825161, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
[17:11:57] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[17:11:57] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[17:11:57] /opt/brazil-pkg-cache/packages/AIAlgorithmsMXNet/AIAlgorithmsMXNet-1.4.x_ecl_Cuda_11.1.x.441.0/AL2_x86_64/generic-flavor/src/src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
#metrics {"StartTime": 1750525916.9981732, "EndTime": 1750525917.8825161, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750525917.0971172, "EndTime": 1750525917.8826208, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750525917.8827028, "EndTime": 1750525917.8951364, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750525917.8825665, "EndTime": 1750525917.8966556, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750525917.8951838, "EndTime": 1750525917.9052558, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750525917.0971172, "EndTime": 1750525917.8826208, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750525917.8827028, "EndTime": 1750525917.8951364, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750525917.8825665, "EndTime": 1750525917.8966556, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750525917.8951838, "EndTime": 1750525917.9052558, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750525917.8970253, "EndTime": 1750525917.9071448, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750525917.9071968, "EndTime": 1750525917.921594, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750525917.9056203, "EndTime": 1750525917.9278114, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}
#metrics {"StartTime": 1750525916.94866, "EndTime": 1750525917.9344277, "Dimensions": {"Algorithm": "ICModel", "Host": "UNKNOWN", "Operation": "scoring"}, "Metrics": {"invocations.count": {"sum": 1.0, "count": 1, "min": 1, "max": 1}}}

In [97]:
%%time
# merge inferences with s3_input_csv
merge_inferences_with_input_csv(s3_input_csv = input_csv, s3_inferences_loc = s3_transform_out)

'aai-540-data'

'ground_truth/2014/5'

'labels.csv'

'merged_inferences.csv'

'ground_truth/2014/5/merged_inferences.csv'

File uploaded to s3://aai-540-data/ground_truth/2014/5/merged_inferences.csv
CPU times: user 20.5 s, sys: 988 ms, total: 21.5 s
Wall time: 2min 17s

In [98]:
# download merged_inferences.csv and show classifcation report
merged_df = pd.read_csv("s3://aai-540-data/ground_truth/2014/5/merged_inferences.csv")
# generate classification metrics based on label_enc for now
report = classification_report(merged_df['label'], merged_df['pred_label'])

print(report)

              precision    recall  f1-score   support

        bird       0.95      0.63      0.76       807
      bobcat       0.05      0.50      0.09        12
         cat       0.00      0.00      0.00         0
      coyote       0.12      0.68      0.21       152
        deer       1.00      0.07      0.12      1226
         dog       0.00      0.00      0.00         0
       empty       0.00      0.00      0.00         8
         fox       0.00      0.00      0.00        12
      insect       0.00      0.00      0.00         6
      lizard       0.00      0.00      0.00        16
     opossum       0.00      0.00      0.00         0
      rabbit       0.74      0.78      0.76       159
     raccoon       0.03      0.75      0.06         4
      rodent       0.82      0.73      0.77        37
       skunk       0.44      0.57      0.50         7
    squirrel       0.00      0.00      0.00         0

    accuracy                           0.35      2446
   macro avg       0.26      0.29      0.20      2446
weighted avg       0.88      0.35      0.39      2446

/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/opt/conda/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [100]:
!aws sagemaker list-image-versions \
  --image-name sagemaker-scikit-learn \
  --region {region}

An error occurred (ResourceNotFound) when calling the ListImageVersions operation: Image with ARN arn:aws:sagemaker:us-east-1:324183265896:image/sagemaker-scikit-learn does not exist

In [104]:
image_uri = sagemaker.image_uris.retrieve(
    framework='sklearn',        # or 'xgboost', 'pytorch', etc.
    region=region,
    version='1.2-1',            # Specify the version you need
    py_version='py3',           # Specify Python version if required
       # Use 'processing' for processing jobs
)

print(image_uri)

INFO:sagemaker.image_uris:Defaulting to only supported image scope: cpu.

683313688378.dkr.ecr.us-east-1.amazonaws.com/sagemaker-scikit-learn:1.2-1-cpu-py3

In [105]:
from sagemaker.processing import ScriptProcessor, ProcessingInput, ProcessingOutput

# Define your processing container (can use a built-in or custom image)
script_processor = ScriptProcessor(
    command=['python3'],
    image_uri=image_uri,  # e.g., a scikit-learn or custom image
    role=role,
    instance_count=1,
    instance_type='ml.m5.xlarge'
)

In [107]:
!pwd

/home/sagemaker-user/aai-540-su25-group4/experiments/geoffrey

In [118]:
# Run the processing job
script_processor.run(
    code='../../src/evaluation/evaluate.py',  # Your processing script
    inputs=[
        # S3 location of batch transform predictions files
        ProcessingInput(
            source="s3://aai-540-data/ground_truth/2012/5/batch_transform_output/",       # S3 bucket with predictions
            destination='/opt/ml/processing/input_predictions'        # Where the script will read input
        ),
        
        # S3 location of the ground truth labels for the images in this set
        ProcessingInput(
            source="s3://aai-540-data/ground_truth/2012/5/labels.csv",
            destination='/opt/ml/processing/true_labels'
        ),

        # Label Mapping
        ProcessingInput(
            source="s3://aai-540-data/dev_split/label_mapping.json",
            destination='/opt/ml/processing/label_mapping'
        )
    ],
    outputs=[
        ProcessingOutput(
            source='/opt/ml/processing/output',           # Where the script will write output
            destination="s3://aai-540-data/ground_truth/2012/5/tmp_processing_out/"     # S3 bucket to store results
        )
    ]
)

INFO:sagemaker:Creating processing-job with name sagemaker-scikit-learn-2025-06-22-08-02-58-072

............[2025-06-22 08:05:00.602209] Script has started.
INFO:root:Script has started at 2025-06-22 08:05:00.602244.
Number of files in /opt/ml/processing/input_predictions: 4025
Processed 3 prediction files so far, here is the dataframe
                                     filename                                         prediction
0  58bb8a9b-23d2-11e8-a6a3-ec086b02610b_0.jpg  [0.9935277104377741, 1.333773314016184e-09, 2....
1  59f5fea9-23d2-11e8-a6a3-ec086b02610b_0.jpg  [1.067010513855345e-16, 1.0, 5.073130725221037...
2  588f66cb-23d2-11e8-a6a3-ec086b02610b_0.jpg  [0.00030680140480300003, 8.514827243288892e-08...
                                     filename  ... pred_label
0  58bb8a9b-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...        cat
1  59f5fea9-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...    opossum
2  588f66cb-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...   squirrel
3  59a49c51-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...    opossum
4  5a0e35e8-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...        cat
[5 rows x 4 columns]
preds_df shape:(4025, 4)
Loaded ground truth with 4025 records
True Labels data shape: (4025, 9)
                                     filename  ...            timestamp
0  59830994-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...  2012-05-01 01:01:22
1  59f12a76-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...  2012-05-01 01:01:23
2  59e77e94-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...  2012-05-01 01:01:24
3  593d6a1f-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...  2012-05-01 04:27:31
4  5874d51b-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...  2012-05-01 04:27:32
[5 rows x 9 columns]
Merged data shape: (4025, 12)
Merged data head
                                     filename  ...            timestamp
0  58bb8a9b-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...  2012-05-29 09:34:55
1  59f5fea9-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...  2012-05-26 21:33:50
2  588f66cb-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...  2012-05-17 07:36:14
3  59a49c51-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...  2012-05-21 21:27:55
4  5a0e35e8-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...  2012-05-20 07:44:32
[5 rows x 12 columns]
Accuracy: 0.7893167701863354
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
{'bird': {'precision': 0.08148148148148149, 'recall': 0.6470588235294118, 'f1-score': 0.14473684210526316, 'support': 17}, 'bobcat': {'precision': 0.776, 'recall': 0.8128491620111732, 'f1-score': 0.7939972714870396, 'support': 358}, 'cat': {'precision': 0.7985524728588661, 'recall': 0.6268939393939394, 'f1-score': 0.7023872679045093, 'support': 1056}, 'coyote': {'precision': 0.7592067988668555, 'recall': 0.7382920110192838, 'f1-score': 0.7486033519553073, 'support': 363}, 'dog': {'precision': 0.5644171779141104, 'recall': 0.7540983606557377, 'f1-score': 0.6456140350877193, 'support': 122}, 'empty': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1}, 'fox': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 1}, 'opossum': {'precision': 0.9859154929577465, 'recall': 0.8687943262411347, 'f1-score': 0.9236569274269556, 'support': 1128}, 'rabbit': {'precision': 0.875, 'recall': 0.937007874015748, 'f1-score': 0.9049429657794676, 'support': 381}, 'raccoon': {'precision': 0.8454545454545455, 'recall': 0.8878281622911695, 'f1-score': 0.8661233993015135, 'support': 419}, 'rodent': {'precision': 0.0, 'recall': 0.0, 'f1-score': 0.0, 'support': 7}, 'skunk': {'precision': 0.5555555555555556, 'recall': 0.8333333333333334, 'f1-score': 0.6666666666666667, 'support': 6}, 'squirrel': {'precision': 0.46488294314381273, 'recall': 0.8373493975903614, 'f1-score': 0.5978494623655913, 'support': 166}, 'accuracy': 0.7893167701863354, 'macro avg': {'precision': 0.515882036017921, 'recall': 0.6110388761600994, 'f1-score': 0.5380444761600026, 'support': 4025}, 'weighted avg': {'precision': 0.83159070626468, 'recall': 0.7893167701863354, 'f1-score': 0.8029211012709054, 'support': 4025}}
Done executing script

In [125]:
# Run the processing job
script_processor.run(
    code='../../src/evaluation/evaluate.py',  # Your processing script
    inputs=[
        # S3 location of batch transform predictions files
        ProcessingInput(
            source="s3://aai-540-data/ground_truth/2013/8/batch_transform_out/",       # S3 bucket with predictions
            destination='/opt/ml/processing/input_predictions'        # Where the script will read input
        ),
        
        # S3 location of the ground truth labels for the images in this set
        ProcessingInput(
            source="s3://aai-540-data/ground_truth/2013/8/labels.csv",
            destination='/opt/ml/processing/true_labels'
        ),

        # Label Mapping
        ProcessingInput(
            source="s3://aai-540-data/dev_split/label_mapping.json", # can only be changed if new classes are added, or model traininig is restarted
            destination='/opt/ml/processing/label_mapping'
        )
    ],
    outputs=[
        ProcessingOutput(
            source='/opt/ml/processing/output',           # Where the script will write output
            destination="s3://aai-540-data/ground_truth/2013/8/evaluation/"     # S3 bucket to store results
        )
    ]
)

INFO:sagemaker:Creating processing-job with name sagemaker-scikit-learn-2025-06-22-11-31-34-176

.............[2025-06-22 11:33:39.068136] Script has started.
INFO:root:Script has started at 2025-06-22 11:33:39.068173.
Number of files in /opt/ml/processing/input_predictions: 1009
Processed 3 prediction files so far, here is the dataframe
                                     filename                                         prediction
0  596ef066-23d2-11e8-a6a3-ec086b02610b_0.jpg  [0.005764931906014001, 1.375003762404958e-06, ...
1  599be95b-23d2-11e8-a6a3-ec086b02610b_0.jpg  [0.263194501399993, 0.027892537415027, 0.01378...
2  594b600d-23d2-11e8-a6a3-ec086b02610b_0.jpg  [7.750131203465571e-08, 7.856457671928663e-12,...
                                     filename                                         prediction
0  596ef066-23d2-11e8-a6a3-ec086b02610b_0.jpg  [0.005764931906014001, 1.375003762404958e-06, ...
1  599be95b-23d2-11e8-a6a3-ec086b02610b_0.jpg  [0.263194501399993, 0.027892537415027, 0.01378...
2  594b600d-23d2-11e8-a6a3-ec086b02610b_0.jpg  [7.750131203465571e-08, 7.856457671928663e-12,...
3  5976a2ef-23d2-11e8-a6a3-ec086b02610b_0.jpg  [0.015222396701574001, 0.00024270509311400003,...
4  59673507-23d2-11e8-a6a3-ec086b02610b_0.jpg  [8.113171467982738e-09, 2.3702499163391622e-07...
pred probs df shape:(1009, 2)
 (step 1) pred probs df shape: (1009, 2)
 (step 2) True Labels data shape: (1009, 9)
                                     filename  ...            timestamp
0  597b4ab1-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...  2013-08-01 10:20:55
1  59f946a5-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...  2013-08-01 10:20:57
2  59df5b5c-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...  2013-08-01 10:21:04
3  59a30c62-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...  2013-08-01 10:21:05
4  597cd4dd-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...  2013-08-01 10:21:06
[5 rows x 9 columns]
 (step3) Merged data shape : (1009, 10)
                                     filename  ...            timestamp
0  596ef066-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...  2013-08-14 10:56:23
1  599be95b-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...  2013-08-24 03:59:26
2  594b600d-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...  2013-08-14 20:18:12
3  5976a2ef-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...  2013-08-13 09:52:00
4  59673507-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...  2013-08-16 16:42:17
[5 rows x 10 columns]
 (step4) Merged data shape: (1009, 12)
                                     filename  ... pred_label
0  596ef066-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...       bird
1  599be95b-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...    raccoon
2  594b600d-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...     coyote
3  5976a2ef-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...    raccoon
4  59673507-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...       bird
[5 rows x 12 columns]
 (step5) METRICS CALCULATION
 (step5.1) Class-Restricted metrics - Evaluate only on labels available during training
 (step5.1) class_restriced df shape : (874, 12)
                                     filename  ... pred_label
0  596ef066-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...       bird
1  599be95b-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...    raccoon
2  594b600d-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...     coyote
3  5976a2ef-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...    raccoon
4  59673507-23d2-11e8-a6a3-ec086b02610b_0.jpg  ...       bird
[5 rows x 12 columns]
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
              precision    recall  f1-score   support
        bird       0.72      0.59      0.65       102
      bobcat       0.70      0.70      0.70        37
         cat       0.00      0.00      0.00         0
      coyote       0.10      0.92      0.17        50
        deer       1.00      0.02      0.04       561
         dog       0.00      0.00      0.00         0
       empty       0.00      0.00      0.00         0
     opossum       0.00      0.00      0.00         0
      rabbit       0.70      0.75      0.72        68
     raccoon       0.00      0.00      0.00         0
      rodent       1.00      0.28      0.43        18
       skunk       1.00      0.58      0.73        38
    squirrel       0.00      0.00      0.00         0
    accuracy                           0.25       874
   macro avg       0.40      0.30      0.27       874
weighted avg       0.88      0.25      0.24       874
 (step5.2) Novelty Ratio Metric: portion of the new dataset that is unfamiliar to the model given a confidence threshold=0.7
 (step5.2) novelty ratio : 0.21902874132804756
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
Done executing script

In [153]:
# Run the processing job
script_processor.run(
    code='../../src/evaluation/evaluate.py',  # Your processing script
    inputs=[
        # S3 location of batch transform predictions files
        ProcessingInput(
            source="s3://aai-540-data/ground_truth/2013/9/batch_transform_out/",       # S3 bucket with predictions
            destination='/opt/ml/processing/input_predictions'        # Where the script will read input
        ),
        
        # S3 location of the ground truth labels for the images in this set
        ProcessingInput(
            source="s3://aai-540-data/ground_truth/2013/9/labels.csv",
            destination='/opt/ml/processing/true_labels'
        ),

        # Label Mapping
        ProcessingInput(
            source="s3://aai-540-data/dev_split/label_mapping.json", # can only be changed if new classes are added, or model traininig is restarted
            destination='/opt/ml/processing/label_mapping'
        )
    ],
    outputs=[
        ProcessingOutput(
            source='/opt/ml/processing/output',           # Where the script will write output
            destination="s3://aai-540-data/ground_truth/2013/9/evaluation/"     # S3 bucket to store results
        )
    ]
)

INFO:sagemaker:Creating processing-job with name sagemaker-scikit-learn-2025-06-22-18-44-53-532

............[2025-06-22 18:46:47.635549] Script has started.
INFO:root:Script has started at 2025-06-22 18:46:47.635586.
Number of files in /opt/ml/processing/input_predictions: 702
pred probs df shape:(702, 2)
 (step 1) pred probs df shape: (702, 2)
 (step 2) True Labels data shape: (702, 9)
 (step3) Merged data shape : (702, 10)
 (step4) Merged data shape with preds: (702, 12)
 (step5) METRICS CALCULATION
 (step5.1) Class-Restricted metrics - Evaluate only on labels available during training
 (step5.1) class_restriced df shape : (605, 12)
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
              precision    recall  f1-score   support
        bird       0.58      0.37      0.45        71
      bobcat       0.55      0.95      0.69        37
         cat       0.00      0.00      0.00         0
      coyote       0.30      0.87      0.45        70
        deer       1.00      0.03      0.06       253
         dog       0.00      0.00      0.00         0
       empty       0.00      0.00      0.00         7
     opossum       0.00      0.00      0.00         0
      rabbit       0.89      0.72      0.80       122
     raccoon       0.12      0.83      0.21         6
      rodent       0.67      0.27      0.38        15
       skunk       0.96      0.96      0.96        24
    squirrel       0.00      0.00      0.00         0
    accuracy                           0.41       605
   macro avg       0.39      0.38      0.31       605
weighted avg       0.79      0.41      0.38       605
 (step5.2) Novelty Ratio Metric: portion of the new dataset that is unfamiliar to the model given a confidence threshold=0.7
 (step5.2) novelty ratio : 0.2621082621082621
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/miniconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
usage: evaluate.py [-h] --pipeline-timestamp PIPELINE_TIMESTAMP --year-month
                   YEAR_MONTH
evaluate.py: error: the following arguments are required: --pipeline-timestamp, --year-month

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:2                                                                                    │
│                                                                                                  │
│    1 # Run the processing job                                                                    │
│ ❱  2 script_processor.run(                                                                       │
│    3 │   code='../../src/evaluation/evaluate.py',  # Your processing script                      │
│    4 │   inputs=[                                                                                │
│    5 │   │   # S3 location of batch transform predictions files                                  │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/workflow/pipeline_context.py:346 in wrapper    │
│                                                                                                  │
│   343 │   │   │                                                                                  │
│   344 │   │   │   return _StepArguments(retrieve_caller_name(self_instance), run_func, *args,    │
│   345 │   │                                                                                      │
│ ❱ 346 │   │   return run_func(*args, **kwargs)                                                   │
│   347 │                                                                                          │
│   348 │   return wrapper                                                                         │
│   349                                                                                            │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/processing.py:688 in run                       │
│                                                                                                  │
│    685 │   │   )                                                                                 │
│    686 │   │   self.jobs.append(self.latest_job)                                                 │
│    687 │   │   if wait:                                                                          │
│ ❱  688 │   │   │   self.latest_job.wait(logs=logs)                                               │
│    689 │                                                                                         │
│    690 │   def _include_code_in_inputs(self, inputs, code, kms_key=None):                        │
│    691 │   │   """Converts code to appropriate input and includes in input list.                 │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/processing.py:1113 in wait                     │
│                                                                                                  │
│   1110 │   │                                                                                     │
│   1111 │   │   """                                                                               │
│   1112 │   │   if logs:                                                                          │
│ ❱ 1113 │   │   │   self.sagemaker_session.logs_for_processing_job(self.job_name, wait=True)      │
│   1114 │   │   else:                                                                             │
│   1115 │   │   │   self.sagemaker_session.wait_for_processing_job(self.job_name)                 │
│   1116                                                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/session.py:6234 in logs_for_processing_job     │
│                                                                                                  │
│   6231 │   │   │   │   │   state = LogState.JOB_COMPLETE                                         │
│   6232 │   │                                                                                     │
│   6233 │   │   if wait:                                                                          │
│ ❱ 6234 │   │   │   _check_job_status(job_name, description, "ProcessingJobStatus")               │
│   6235 │   │   │   if dot:                                                                       │
│   6236 │   │   │   │   print()                                                                   │
│   6237                                                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/session.py:8835 in _check_job_status           │
│                                                                                                  │
│   8832 │   │   │   │   allowed_statuses=["Completed", "Stopped"],                                │
│   8833 │   │   │   │   actual_status=status,                                                     │
│   8834 │   │   │   )                                                                             │
│ ❱ 8835 │   │   raise exceptions.UnexpectedStatusException(                                       │
│   8836 │   │   │   message=message,                                                              │
│   8837 │   │   │   allowed_statuses=["Completed", "Stopped"],                                    │
│   8838 │   │   │   actual_status=status,                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
UnexpectedStatusException: Error for Processing job sagemaker-scikit-learn-2025-06-22-18-44-53-532: Failed. Reason:
AlgorithmError: , exit code: 2. Check troubleshooting guide for common errors:
https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-python-sdk-troubleshooting.html

In [141]:
from datetime import datetime

In [201]:
import time
def publish_metrics(metrics_dict, timestamp, year_month):
    import calendar

    cloudwatch = boto3.client('cloudwatch')
    namespace = 'AnimalClassifier/MonthlyMetrics'
    #timestamp = datetime.utcnow()
    
    metric_data = []
    #for metric_name, value in metrics_dict.items():
    for metric_name, value in metrics_json['multiclass_classification_metrics'].items():
        metric_data.append({
            'MetricName': metric_name,
            'Dimensions': [
                {'Name': 'Pipeline', 'Value': 'MonthlyEvaluation'},
                {'Name': 'YearMonth', 'Value': year_month}  # Added dimension
            ],
            'Value': value['value'],
            'Unit': 'None',
            'Timestamp': timestamp
        })
    cloudwatch.put_metric_data(Namespace=namespace, MetricData=metric_data)

In [151]:
# load metrics json from s3 bucket, but this one is for trial
with open('tmp/multiclass_metrics-2012-06.json', 'r') as file:
    metrics_json = json.load(file)
publish_metrics(metrics_json, "2012-06")

/tmp/ipykernel_6414/3182418243.py:6: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow()

In [152]:
# load metrics json from s3 bucket, but this one is for trial
with open('tmp/multiclass_metrics-2013-09.json', 'r') as file:
    metrics_json = json.load(file)
publish_metrics(metrics_json, "2013-09")

/tmp/ipykernel_6414/3182418243.py:6: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow()

In [144]:
metrics_json

{'multiclass_classification_metrics': {'accuracy': {'value': 0.4132231404958678,
   'standard_deviation': 'NaN'},
  'f1-weighted': {'value': 0.38302977767278157, 'standard_deviation': 'NaN'},
  'novelty_ratio': {'value': 0.2621082621082621, 'standard_deviation': 'NaN'}}}

In [145]:
publish_metrics(metrics_json, "2013-09")

/tmp/ipykernel_6414/433927692.py:4: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow()

In [146]:
# load metrics json from s3 bucket, but this one is for trial
with open('tmp/multiclass_metrics-2013-08.json', 'r') as file:
    metrics_json = json.load(file)
publish_metrics(metrics_json, "2013-08")

/tmp/ipykernel_6414/433927692.py:4: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  timestamp = datetime.utcnow()

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:4                                                                                    │
│                                                                                                  │
│   1 # load metrics json from s3 bucket, but this one is for trial                                │
│   2 with open('tmp/multiclass_metrics-2013-08.json', 'r') as file:                               │
│   3 │   metrics_json = json.load(file)                                                           │
│ ❱ 4 publish_metrics(metrics_json, "2013-08")                                                     │
│   5                                                                                              │
│                                                                                                  │
│ in publish_metrics:8                                                                             │
│                                                                                                  │
│    5 │                                                                                           │
│    6 │   metric_data = []                                                                        │
│    7 │   #for metric_name, value in metrics_dict.items():                                        │
│ ❱  8 │   for metric_name, value in metrics_json['multiclass_classification_metrics'].items():    │
│    9 │   │   metric_data.append({                                                                │
│   10 │   │   │   'MetricName': metric_name,                                                      │
│   11 │   │   │   'Dimensions': [                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'multiclass_classification_metrics'

In [131]:
for metric_name, value in metrics_json.items():
    print(f"metric_name: {metric_name}

'multiclass_classification_metrics'

{'accuracy': {'value': 0.8304668304668305, 'standard_deviation': 'NaN'},
 'f1-weighted': {'value': 0.8463272260888135, 'standard_deviation': 'NaN'},
 'novelty_ratio': {'value': 0.08722358722358722, 'standard_deviation': 'NaN'}}

In [232]:
time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())

'2025-06-23T08:19:35Z'

In [137]:
for metric_name, value in metrics_json['multiclass_classification_metrics'].items():
    print(f"metric_name: {metric_name}")
    print(f"value: {value['value']}")

metric_name: accuracy
value: 0.8304668304668305
metric_name: f1-weighted
value: 0.8463272260888135
metric_name: novelty_ratio
value: 0.08722358722358722

In [302]:
def publish_metrics(metrics_dict, timestamp, year_month, namespace = 'AnimalClassifier/v7/MonthlyMetrics', sample_count = 0):
    import calendar
   
    
    cloudwatch = boto3.client('cloudwatch')
    timestamp = time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())
    print(f"\ttimestamp: {timestamp}")
    # metric data with Year Month
    metric_data = []
    # add year month dimension for easy viewing on cloud watch
    for metric_name, value in metrics_dict['multiclass_classification_metrics'].items():
        metric_data.append({
            'MetricName': metric_name,
            'Dimensions': [
                {'Name': 'YearMonth', 'Value': year_month}  # Added dimension
            ],
            'Value': float("{:.4f}".format(value['value'])),
            'Unit': 'None',
            'Timestamp': timestamp,
        })
    # add number of samples
    metric_data.append({
        'MetricName': "sample_count",
        'Dimensions': [
            {'Name': 'YearMonth', 'Value': year_month}  # Added dimension
        ],
        'Value': sample_count,
        'Unit': 'Count',
        'Timestamp': timestamp,
    })
    #print(json.dumps(metric_data, indent=3))
    cloudwatch.put_metric_data(Namespace=namespace, MetricData=metric_data)

    metric_data = []
    # remove extra dimensions 
    for metric_name, value in metrics_dict['multiclass_classification_metrics'].items():
        metric_data.append({
            'MetricName': metric_name,
            'Dimensions': [],
            'Value': float("{:.4f}".format(value['value'])),
            'Unit': 'None',
            'Timestamp': timestamp,
        })
    metric_data.append({
        'MetricName': "sample_count",
        'Dimensions': [],
        'Value': sample_count,
        'Unit': 'Count',
        'Timestamp': timestamp,
    })
    
    
     
    #print(json.dumps(metric_data, indent=3))
    cloudwatch.put_metric_data(Namespace=namespace, MetricData=metric_data)

In [154]:
s3_production_meta_uri = f"s3://{bucket_name}/dev_split/production-meta.csv"

df = pd.read_csv(s3_production_meta_uri)
df['timestamp'] = pd.to_datetime(df['date_captured'])

# Generate list of year-months where there were image samples present
sample_year_months = df['timestamp'].dt.to_period('M').unique()
sample_year_months_str = sample_year_months.astype(str).tolist()

In [305]:
i=0
for year_month in sample_year_months_str:

#for year_month in ['2015-03', '2015-04', '2015-05']:
    year_str, month_str = year_month.split('-')
    year = int(year_str)
    month = int(month_str)
    
    s3_monthly_eval_loc = f"s3://{bucket_name}/ground_truth/{year}/{month}/evaluation"
    s3_monthly_metrics_uri = f"{s3_monthly_eval_loc}/multiclass_metrics.json"
    s3_monthly_timestamp_uri = f"{s3_monthly_eval_loc}/timing_info.json"
    s3_monthly_merged_uri = f"{s3_monthly_eval_loc}/merged_inferences.csv"
    
    print(year_month)
    
    # load metrics json from s3 bucket, but this one is for trial
    metrics_json = pd.read_json(s3_monthly_metrics_uri)
    for metric_name, value in metrics_json['multiclass_classification_metrics'].items():
        print(f"\tmetric_name: {metric_name}  value: {value['value']}")

    # get number of samples for this month
    merged_df = pd.read_csv(s3_monthly_merged_uri)
    num_samples = len(merged_df)
    print(merged_df.shape)

    obj = s3_client.get_object(Bucket=bucket_name, Key=f'ground_truth/{year}/{month}/evaluation/timing_info.json')
    timing_info = json.loads(obj['Body'].read().decode('utf-8'))
    timestamp = timing_info['simulated_timestamp']
    #print("\tPipeline/Evaluation Timestamp:", timestamp)

    
    publish_metrics(metrics_json, timestamps[i], year_month, namespace='Experiments/AAI-540/v1', sample_count = num_samples)
    i = i+ 1
    time.sleep(60)

2012-05
	metric_name: accuracy  value: 0.7895129224652081
	metric_name: f1-weighted  value: 0.8031737868823131
	metric_name: novelty_ratio  value: 0.11751552795031
(4025, 14)
	timestamp: 2025-06-23T16:39:41Z
2012-06
	metric_name: accuracy  value: 0.8304668304668301
	metric_name: f1-weighted  value: 0.8463272260888131
	metric_name: novelty_ratio  value: 0.087223587223587
(814, 14)
	timestamp: 2025-06-23T16:40:41Z
2012-07
	metric_name: accuracy  value: 0.46969696969696906
	metric_name: f1-weighted  value: 0.39850184328182603
	metric_name: novelty_ratio  value: 0.08955223880597
(67, 14)
	timestamp: 2025-06-23T16:41:42Z

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:34                                                                                   │
│                                                                                                  │
│   31 │                                                                                           │
│   32 │   publish_metrics(metrics_json, timestamps[i], year_month, namespace='Experiments/AAI-    │
│   33 │   i = i+ 1                                                                                │
│ ❱ 34 │   time.sleep(60)                                                                          │
│   35                                                                                             │
│   36                                                                                             │
│   37                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyboardInterrupt

In [306]:
# get number of samples for this month
merged_df = pd.read_csv(s3_monthly_merged_uri)
num_samples = len(merged_df)
print(merged_df.shape)

merged_df.head()

(67, 14)

,Unnamed: 0,filename,prediction,label,category_id,bbox,image_id,location,split_type,date_captured,timestamp,pred_label_enc,pred_label,max_pred_prob
0,0,59e5dfee-23d2-11e8-a6a3-ec086b02610b_0.jpg,"[1.5849481371787977e-07, 3.524526164255803e-07...",coyote,9,"[1091.2, 950.4, 492.8, 320.0]",59e5dfee-23d2-11e8-a6a3-ec086b02610b,0,val,2012-07-16 11:58:40,2012-07-16 11:58:40,9,coyote,0.999264
1,1,595f792d-23d2-11e8-a6a3-ec086b02610b_0.jpg,"[5.679333114905205e-10, 2.165613910420916e-09,...",fox,51,"[1143.736972332, 690.2729744911, 186.424088001...",595f792d-23d2-11e8-a6a3-ec086b02610b,66,train,2012-07-26 00:16:00,2012-07-26 00:16:00,2,squirrel,0.994768
2,2,59817afe-23d2-11e8-a6a3-ec086b02610b_0.jpg,"[0.000281308079138, 2.131726614607032e-05, 0.8...",car,33,"[0, 0, 2560, 1920]",59817afe-23d2-11e8-a6a3-ec086b02610b,0,val,2012-07-28 13:15:16,2012-07-28 13:15:16,2,squirrel,0.841582
3,3,5a1caf4c-23d2-11e8-a6a3-ec086b02610b_0.jpg,"[0.000746714998967, 6.764229328837246e-05, 0.0...",car,33,"[0, 0, 2560, 1920]",5a1caf4c-23d2-11e8-a6a3-ec086b02610b,0,val,2012-07-25 10:26:17,2012-07-25 10:26:17,9,coyote,0.946418
4,4,59fe2100-23d2-11e8-a6a3-ec086b02610b_0.jpg,"[0.00013539099018000002, 1.4814781025052072e-0...",car,33,"[0, 0, 2560, 1920]",59fe2100-23d2-11e8-a6a3-ec086b02610b,0,val,2012-07-28 17:14:16,2012-07-28 17:14:16,9,coyote,0.793638

In [307]:
class_restrict_df = merged_df[merged_df['label'].isin(CURRENT_LABEL_MAP.keys())] # known classes
class_restrict_df

,Unnamed: 0,filename,prediction,label,category_id,bbox,image_id,location,split_type,date_captured,timestamp,pred_label_enc,pred_label,max_pred_prob
0,0,59e5dfee-23d2-11e8-a6a3-ec086b02610b_0.jpg,"[1.5849481371787977e-07, 3.524526164255803e-07...",coyote,9,"[1091.2, 950.4, 492.8, 320.0]",59e5dfee-23d2-11e8-a6a3-ec086b02610b,0,val,2012-07-16 11:58:40,2012-07-16 11:58:40,9,coyote,0.999264
2,2,59817afe-23d2-11e8-a6a3-ec086b02610b_0.jpg,"[0.000281308079138, 2.131726614607032e-05, 0.8...",car,33,"[0, 0, 2560, 1920]",59817afe-23d2-11e8-a6a3-ec086b02610b,0,val,2012-07-28 13:15:16,2012-07-28 13:15:16,2,squirrel,0.841582
3,3,5a1caf4c-23d2-11e8-a6a3-ec086b02610b_0.jpg,"[0.000746714998967, 6.764229328837246e-05, 0.0...",car,33,"[0, 0, 2560, 1920]",5a1caf4c-23d2-11e8-a6a3-ec086b02610b,0,val,2012-07-25 10:26:17,2012-07-25 10:26:17,9,coyote,0.946418
4,4,59fe2100-23d2-11e8-a6a3-ec086b02610b_0.jpg,"[0.00013539099018000002, 1.4814781025052072e-0...",car,33,"[0, 0, 2560, 1920]",59fe2100-23d2-11e8-a6a3-ec086b02610b,0,val,2012-07-28 17:14:16,2012-07-28 17:14:16,9,coyote,0.793638
5,5,59d0e170-23d2-11e8-a6a3-ec086b02610b_0.jpg,"[1.035461778542412e-07, 4.370725719127222e-07,...",bobcat,6,"[338.0, 947.0, 1223.9808044434, 537.0260009766]",59d0e170-23d2-11e8-a6a3-ec086b02610b,29,train,2012-07-19 22:47:00,2012-07-19 22:47:00,8,bobcat,0.999962
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,62,599d7b79-23d2-11e8-a6a3-ec086b02610b_0.jpg,"[9.471344674238936e-05, 0.00047138935769900004...",car,33,"[0, 0, 2560, 1920]",599d7b79-23d2-11e8-a6a3-ec086b02610b,0,val,2012-07-17 10:06:45,2012-07-17 10:06:45,9,coyote,0.931680
63,63,59d4185a-23d2-11e8-a6a3-ec086b02610b_0.jpg,"[7.812861468892152e-08, 2.202542148665998e-08,...",skunk,7,"[1283.2, 908.8, 505.6, 803.2]",59d4185a-23d2-11e8-a6a3-ec086b02610b,0,val,2012-07-31 03:54:08,2012-07-31 03:54:08,13,skunk,0.999961
64,64,5a0e3467-23d2-11e8-a6a3-ec086b02610b_0.jpg,"[1.9475981389405202e-05, 8.962134501189212e-08...",coyote,9,"[1164.8, 876.8, 457.6, 284.8]",5a0e3467-23d2-11e8-a6a3-ec086b02610b,0,val,2012-07-26 21:40:59,2012-07-26 21:40:59,9,coyote,0.999647
65,65,59c31c46-23d2-11e8-a6a3-ec086b02610b_0.jpg,"[1.0482525425459238e-07, 9.057627039510407e-07...",car,33,"[0, 0, 2560, 1920]",59c31c46-23d2-11e8-a6a3-ec086b02610b,0,val,2012-07-28 17:11:38,2012-07-28 17:11:38,2,squirrel,0.922678
66,66,59a6294a-23d2-11e8-a6a3-ec086b02610b_0.jpg,"[9.022125595947729e-05, 5.756087944064349e-07,...",coyote,9,"[771.2, 883.2, 515.2, 288.0]",59a6294a-23d2-11e8-a6a3-ec086b02610b,0,val,2012-07-31 03:49:36,2012-07-31 03:49:36,9,coyote,0.945143

In [310]:
class_restrict_df['prediction'][0]

'[1.5849481371787977e-07, 3.524526164255803e-07, 4.531800268381403e-09, 2.4659904340751382e-08, 1.7818027231442102e-07, 1.940694183133473e-08, 0.000448109291028, 1.172441770336263e-07, 1.1566261548523471e-07, 0.999264180660247, 1.240001434865689e-08, 0.00028632904286400004, 1.323519249751825e-08, 4.8206363345570935e-09, 1.334795172169833e-07, 1.966153746479904e-07, 1.082148948228223e-08]'

In [313]:
import ast

class_restrict_df['prediction'].apply(ast.literal_eval)

0     [1.5849481371787977e-07, 3.524526164255803e-07...
2     [0.000281308079138, 2.131726614607032e-05, 0.8...
3     [0.000746714998967, 6.764229328837246e-05, 0.0...
4     [0.00013539099018000002, 1.4814781025052072e-0...
5     [1.035461778542412e-07, 4.370725719127222e-07,...
                            ...
62    [9.471344674238936e-05, 0.00047138935769900004...
63    [7.812861468892152e-08, 2.202542148665998e-08,...
64    [1.9475981389405202e-05, 8.962134501189212e-08...
65    [1.0482525425459238e-07, 9.057627039510407e-07...
66    [9.022125595947729e-05, 5.756087944064349e-07,...
Name: prediction, Length: 66, dtype: object

In [314]:
pd.DataFrame(class_restrict_df['prediction'].apply(ast.literal_eval).tolist())

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,1.584948e-07,3.524526e-07,4.531800e-09,2.465990e-08,1.781803e-07,1.940694e-08,4.481093e-04,1.172442e-07,1.156626e-07,9.992642e-01,1.240001e-08,2.863290e-04,1.323519e-08,4.820636e-09,1.334795e-07,1.966154e-07,1.082149e-08
1,2.813081e-04,2.131727e-05,8.415824e-01,7.095245e-05,1.920266e-02,2.981413e-04,6.060870e-02,3.696543e-05,8.269687e-04,1.210853e-03,6.973630e-02,3.370333e-03,1.284111e-03,2.776185e-04,1.170780e-03,1.690794e-05,3.675071e-06
2,7.467150e-04,6.764229e-05,1.002451e-02,2.784449e-04,1.501925e-03,1.322232e-04,2.528707e-03,4.316449e-04,6.787872e-03,9.464183e-01,1.471097e-02,8.899930e-03,6.475331e-04,5.954314e-03,7.355264e-04,1.075450e-04,2.619671e-05
3,1.353910e-04,1.481478e-05,1.756280e-02,5.623223e-04,5.476844e-04,1.249618e-04,4.538552e-05,4.908469e-04,1.573699e-02,7.936383e-01,1.617425e-01,1.298982e-03,1.902564e-03,5.384024e-03,7.829026e-04,2.601779e-05,3.500477e-06
4,1.035462e-07,4.370726e-07,2.931364e-06,6.530865e-07,2.543477e-07,6.212451e-07,3.205132e-07,2.159041e-07,9.999619e-01,3.188873e-05,5.714228e-09,1.432656e-07,4.089677e-08,1.284515e-08,5.810434e-07,8.883619e-09,3.538482e-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,9.471345e-05,4.713894e-04,6.969128e-05,6.802730e-03,3.369595e-04,1.683501e-04,7.191902e-03,1.497075e-04,2.045210e-03,9.316800e-01,8.716746e-03,3.875380e-02,4.423182e-04,8.413399e-04,2.124620e-03,9.939572e-05,1.123438e-05
62,7.812861e-08,2.202542e-08,4.756423e-09,3.782807e-05,6.616808e-07,5.477555e-09,3.575273e-10,1.932108e-08,1.150169e-11,1.133387e-08,3.242783e-08,1.519094e-08,1.914983e-07,9.999607e-01,4.785292e-07,3.398923e-10,1.244695e-10
63,1.947598e-05,8.962135e-08,1.182509e-07,3.754463e-05,1.599167e-07,2.091810e-06,2.075606e-04,1.701335e-06,4.124426e-05,9.996474e-01,1.119539e-07,3.162922e-05,1.257462e-06,3.370026e-07,7.454939e-06,1.798301e-06,8.397639e-08
64,1.048253e-07,9.057627e-07,9.226776e-01,8.053174e-06,2.033645e-02,1.215339e-02,5.439324e-04,5.574371e-05,1.694610e-03,1.823273e-02,1.666973e-02,3.099237e-03,1.875225e-03,1.123644e-03,1.523651e-03,4.501291e-06,5.465374e-07
65,9.022126e-05,5.756088e-07,9.700785e-07,4.891913e-02,1.361396e-06,2.737180e-03,7.627847e-07,2.135964e-06,9.554516e-07,9.451430e-01,7.213035e-07,2.103172e-04,1.730921e-03,8.585954e-06,1.138481e-03,1.450946e-05,1.952506e-07

In [282]:
samples_json = {
        "multiclass_classification_metrics": {
            "sample_count": {"value": num_samples, "standard_deviation": "NaN"}
            }
}
pd.DataFrame(samples_json)

                       multiclass_classification_metrics
sample_count  {'value': 67, 'standard_deviation': 'NaN'}

In [285]:
metrics_json = metrics_json.update(samples_json)

In [283]:
metrics_json['multiclass_classification_metrics'].update(samples_json)

In [286]:

metrics_json

In [255]:
i=0
#for year_month in sample_year_months_str:

for year_month in ['2012-05', '2012-06', '2012-07']:
    year_str, month_str = year_month.split('-')
    year = int(year_str)
    month = int(month_str)
    
    s3_monthly_eval_loc = f"s3://{bucket_name}/ground_truth/{year}/{month}/evaluation"
    s3_monthly_metrics_uri = f"{s3_monthly_eval_loc}/multiclass_metrics.json"
    #s3_monthly_timestamp_uri = f"{s3_monthly_eval_loc}/timing_info.json"
    s3_monthly_merged_uri = f"{s3_monthly_eval_loc}/merged_inferences.csv"
    
    
    print(year_month)
    #load metrics json from s3 bucket, but this one is for trial
    metrics_json = pd.read_json(s3_monthly_metrics_uri)
    for metric_name, value in metrics_json['multiclass_classification_metrics'].items():
        print(f"\tmetric_name: {metric_name}  value: {value['value']}")
        

    #obj = s3_client.get_object(Bucket=bucket_name, Key=f'ground_truth/{year}/{month}/evaluation/timing_info.json')
    #timing_info = json.loads(obj['Body'].read().decode('utf-8'))
    #timestamp = timing_info['simulated_timestamp']
    #print("\tPipeline/Evaluation Timestamp:", timestamp)

    # get number of samples for this month
    merged_df = pd.read_csv(s3_monthly_merged_uri)
    num_samples = len(merged_df)
    print(merged_df.shape)

    #samples_json = {'multiclass_classification_metrics':
    #    {'sample_count': {'value': num_samples, 'standard_deviation': 'NaN'}},
    #}

    #print(samples_json)

    #publish_metrics(samples_json, timestamps[i], year_month, namespace='Experiments/AAI-540/v0')
    #i = i+ 1
    #time.sleep(10.0)

2012-05
	metric_name: accuracy  value: 0.7895129224652081
	metric_name: f1-weighted  value: 0.8031737868823131
	metric_name: novelty_ratio  value: 0.11751552795031
(4025, 14)
[
   {
      "MetricName": "accuracy",
      "Dimensions": [
         {
            "Name": "YearMonth",
            "Value": "2012-05"
         }
      ],
      "Value": 0.7895,
      "Unit": "None",
      "Timestamp": "2025-06-23T08:28:24Z"
   },
   {
      "MetricName": "f1-weighted",
      "Dimensions": [
         {
            "Name": "YearMonth",
            "Value": "2012-05"
         }
      ],
      "Value": 0.8032,
      "Unit": "None",
      "Timestamp": "2025-06-23T08:28:24Z"
   },
   {
      "MetricName": "novelty_ratio",
      "Dimensions": [
         {
            "Name": "YearMonth",
            "Value": "2012-05"
         }
      ],
      "Value": 0.1175,
      "Unit": "None",
      "Timestamp": "2025-06-23T08:28:24Z"
   }
]
[
   {
      "MetricName": "accuracy",
      "Dimensions": [],
      "Value": 0.7895,
      "Unit": "None",
      "Timestamp": "2025-06-23T08:28:24Z"
   },
   {
      "MetricName": "f1-weighted",
      "Dimensions": [],
      "Value": 0.8032,
      "Unit": "None",
      "Timestamp": "2025-06-23T08:28:24Z"
   },
   {
      "MetricName": "novelty_ratio",
      "Dimensions": [],
      "Value": 0.1175,
      "Unit": "None",
      "Timestamp": "2025-06-23T08:28:24Z"
   }
]
2012-06
	metric_name: accuracy  value: 0.8304668304668301
	metric_name: f1-weighted  value: 0.8463272260888131
	metric_name: novelty_ratio  value: 0.087223587223587
(814, 14)
[
   {
      "MetricName": "accuracy",
      "Dimensions": [
         {
            "Name": "YearMonth",
            "Value": "2012-06"
         }
      ],
      "Value": 0.8305,
      "Unit": "None",
      "Timestamp": "2025-06-23T08:29:24Z"
   },
   {
      "MetricName": "f1-weighted",
      "Dimensions": [
         {
            "Name": "YearMonth",
            "Value": "2012-06"
         }
      ],
      "Value": 0.8463,
      "Unit": "None",
      "Timestamp": "2025-06-23T08:29:24Z"
   },
   {
      "MetricName": "novelty_ratio",
      "Dimensions": [
         {
            "Name": "YearMonth",
            "Value": "2012-06"
         }
      ],
      "Value": 0.0872,
      "Unit": "None",
      "Timestamp": "2025-06-23T08:29:24Z"
   }
]
[
   {
      "MetricName": "accuracy",
      "Dimensions": [],
      "Value": 0.8305,
      "Unit": "None",
      "Timestamp": "2025-06-23T08:29:24Z"
   },
   {
      "MetricName": "f1-weighted",
      "Dimensions": [],
      "Value": 0.8463,
      "Unit": "None",
      "Timestamp": "2025-06-23T08:29:24Z"
   },
   {
      "MetricName": "novelty_ratio",
      "Dimensions": [],
      "Value": 0.0872,
      "Unit": "None",
      "Timestamp": "2025-06-23T08:29:24Z"
   }
]
2012-07
	metric_name: accuracy  value: 0.46969696969696906
	metric_name: f1-weighted  value: 0.39850184328182603
	metric_name: novelty_ratio  value: 0.08955223880597
(67, 14)
[
   {
      "MetricName": "accuracy",
      "Dimensions": [
         {
            "Name": "YearMonth",
            "Value": "2012-07"
         }
      ],
      "Value": 0.4697,
      "Unit": "None",
      "Timestamp": "2025-06-23T08:30:24Z"
   },
   {
      "MetricName": "f1-weighted",
      "Dimensions": [
         {
            "Name": "YearMonth",
            "Value": "2012-07"
         }
      ],
      "Value": 0.3985,
      "Unit": "None",
      "Timestamp": "2025-06-23T08:30:24Z"
   },
   {
      "MetricName": "novelty_ratio",
      "Dimensions": [
         {
            "Name": "YearMonth",
            "Value": "2012-07"
         }
      ],
      "Value": 0.0896,
      "Unit": "None",
      "Timestamp": "2025-06-23T08:30:24Z"
   }
]
[
   {
      "MetricName": "accuracy",
      "Dimensions": [],
      "Value": 0.4697,
      "Unit": "None",
      "Timestamp": "2025-06-23T08:30:24Z"
   },
   {
      "MetricName": "f1-weighted",
      "Dimensions": [],
      "Value": 0.3985,
      "Unit": "None",
      "Timestamp": "2025-06-23T08:30:24Z"
   },
   {
      "MetricName": "novelty_ratio",
      "Dimensions": [],
      "Value": 0.0896,
      "Unit": "None",
      "Timestamp": "2025-06-23T08:30:24Z"
   }
]

In [251]:
timestamps

['2025-06-23T08:28:24Z',
 '2025-06-23T08:29:24Z',
 '2025-06-23T08:30:24Z',
 '2025-06-23T08:31:24Z',
 '2025-06-23T08:32:24Z',
 '2025-06-23T08:33:24Z',
 '2025-06-23T08:34:24Z',
 '2025-06-23T08:35:24Z',
 '2025-06-23T08:36:24Z',
 '2025-06-23T08:37:24Z',
 '2025-06-23T08:38:24Z',
 '2025-06-23T08:39:24Z',
 '2025-06-23T08:40:24Z',
 '2025-06-23T08:41:24Z',
 '2025-06-23T08:42:24Z',
 '2025-06-23T08:43:24Z',
 '2025-06-23T08:44:24Z',
 '2025-06-23T08:45:24Z',
 '2025-06-23T08:46:24Z',
 '2025-06-23T08:47:24Z',
 '2025-06-23T08:48:24Z',
 '2025-06-23T08:49:24Z',
 '2025-06-23T08:50:24Z',
 '2025-06-23T08:51:24Z',
 '2025-06-23T08:52:24Z',
 '2025-06-23T08:53:24Z',
 '2025-06-23T08:54:24Z',
 '2025-06-23T08:55:24Z',
 '2025-06-23T08:56:24Z',
 '2025-06-23T08:57:24Z',
 '2025-06-23T08:58:24Z',
 '2025-06-23T08:59:24Z',
 '2025-06-23T09:00:24Z',
 '2025-06-23T09:01:24Z',
 '2025-06-23T09:02:24Z']

In [256]:
# Get current UTC time in desired format
current_utc_str = time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())

# Convert to datetime object for calculations
current_utc = datetime.strptime(current_utc_str, '%Y-%m-%dT%H:%M:%SZ')
current_utc

datetime.datetime(2025, 6, 23, 10, 44, 16)